/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_acceuil (void)
{
  GtkWidget *acceuil;
  GtkWidget *fixed1;
  GtkWidget *image9;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;

  acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (acceuil, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (acceuil), _("acceuil"));
  gtk_window_set_position (GTK_WINDOW (acceuil), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (acceuil), FALSE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (acceuil), fixed1);

  image9 = create_pixmap (acceuil, "camera.jpg");
  gtk_widget_show (image9);
  gtk_fixed_put (GTK_FIXED (fixed1), image9, 0, 0);
  gtk_widget_set_size_request (image9, 1000, 704);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 360, 328);
  gtk_widget_set_size_request (button1, 168, 72);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Gestion Hotel"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_Acceuilgestion_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (acceuil, acceuil, "acceuil");
  GLADE_HOOKUP_OBJECT (acceuil, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (acceuil, image9, "image9");
  GLADE_HOOKUP_OBJECT (acceuil, button1, "button1");
  GLADE_HOOKUP_OBJECT (acceuil, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (acceuil, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (acceuil, image1, "image1");
  GLADE_HOOKUP_OBJECT (acceuil, label1, "label1");

  return acceuil;
}

GtkWidget*
create_gestion (void)
{
  GtkWidget *gestion;
  GtkWidget *fixed2;
  GtkWidget *image11;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *button12;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image20;
  GtkWidget *label71;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkWidget *entry1;
  GtkWidget *calendar1;
  GtkWidget *calendar2;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *image10;
  GtkWidget *combobox1;
  GtkWidget *label18;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *button4;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label21;
  GtkWidget *label51;
  GtkWidget *label23;
  GtkWidget *label22;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label10;
  GtkWidget *fixed4;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkWidget *image12;
  GtkWidget *label49;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *button6;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label32;
  GtkWidget *label48;
  GtkWidget *label25;
  GtkWidget *combobox2;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label50;
  GtkWidget *Modifier;
  GtkWidget *alignment35;
  GtkWidget *hbox35;
  GtkWidget *image64;
  GtkWidget *label264;
  GtkWidget *label11;
  GtkWidget *fixed6;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkWidget *image13;
  GtkWidget *label53;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *label40;
  GtkWidget *label35;
  GtkWidget *label41;
  GtkWidget *label36;
  GtkWidget *label42;
  GtkWidget *label37;
  GtkWidget *label43;
  GtkWidget *label38;
  GtkWidget *label44;
  GtkWidget *label46;
  GtkWidget *label52;
  GtkWidget *button7;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label47;
  GtkWidget *combobox3;
  GtkWidget *label13;
  GtkWidget *fixed7;
  GtkWidget *entry5;
  GtkWidget *image14;
  GtkWidget *button8;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label59;
  GtkWidget *label57;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview2;
  GtkWidget *label56;
  GtkWidget *label55;
  GtkWidget *label58;
  GtkWidget *label54;

  gestion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gestion, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (gestion), _("Gestion Hotel"));
  gtk_window_set_position (GTK_WINDOW (gestion), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (gestion), FALSE);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (gestion), fixed2);

  image11 = create_pixmap (gestion, "brown-close-up-hd-wallpaper-surface-172289.jpg");
  gtk_widget_show (image11);
  gtk_fixed_put (GTK_FIXED (fixed2), image11, 0, 640);
  gtk_widget_set_size_request (image11, 1016, 96);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed2), button2, 24, 640);
  gtk_widget_set_size_request (button2, 96, 53);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed2), button12, 896, 640);
  gtk_widget_set_size_request (button12, 96, 53);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button12), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image20 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox11), image20, FALSE, FALSE, 0);

  label71 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label71);
  gtk_box_pack_start (GTK_BOX (hbox11), label71, FALSE, FALSE, 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook1, 0, 8);
  gtk_widget_set_size_request (notebook1, 1576, 632);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1, 128, 88);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed3), calendar1, 168, 184);
  gtk_widget_set_size_request (calendar1, 236, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  calendar2 = gtk_calendar_new ();
  gtk_widget_show (calendar2);
  gtk_fixed_put (GTK_FIXED (fixed3), calendar2, 592, 184);
  gtk_widget_set_size_request (calendar2, 236, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar2),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 50, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton1, 184, 392);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (1, 200, 1200, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton2, 512, 400);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  image10 = create_pixmap (gestion, "bed.jpg");
  gtk_widget_show (image10);
  gtk_fixed_put (GTK_FIXED (fixed3), image10, 0, 0);
  gtk_widget_set_size_request (image10, 1000, 600);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox1, 144, 136);
  gtk_widget_set_size_request (combobox1, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Simple"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Double"));

  label18 = gtk_label_new (_(" <span foreground=\"black\"><b>Date de sortie : </b></span>"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 432, 200);
  gtk_widget_set_size_request (label18, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  label16 = gtk_label_new (_("<span foreground=\"black\"><b>Type de chambre :  </b></span>"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 8, 136);
  gtk_widget_set_size_request (label16, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  label17 = gtk_label_new (_("<span foreground=\"black\"><b>Date d'admission : </b></span>"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 8, 200);
  gtk_widget_set_size_request (label17, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  label19 = gtk_label_new (_(" <span foreground=\"black\"><b>Nombre de chambre : </b></span>\n"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 0, 392);
  gtk_widget_set_size_request (label19, 160, 48);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  label20 = gtk_label_new (_(" <span foreground=\"black\"><b>Prix : </b></span>\n"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 360, 392);
  gtk_widget_set_size_request (label20, 144, 56);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed3), button4, 368, 528);
  gtk_widget_set_size_request (button4, 96, 53);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox4), label21, FALSE, FALSE, 0);

  label51 = gtk_label_new (_("<span foreground=\"blue\"><b><i>Hotel ajout\303\251 avec succ\303\251s</i></b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label51, 0, 0);
  gtk_widget_set_size_request (label51, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label51), TRUE);

  label23 = gtk_label_new (_("<span foreground=\"brown\"><b>Choisir type de chambre !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 288, 112);
  gtk_widget_set_size_request (label23, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  label22 = gtk_label_new (_("<span foreground=\"brown\"><b>Saisir nom !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 240, 64);
  gtk_widget_set_size_request (label22, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  label14 = gtk_label_new (_("<span foreground=\"brown\"><b>Hotel existant!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 256, 8);
  gtk_widget_set_size_request (label14, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  label15 = gtk_label_new (_("<span foreground=\"black\"><b>Nom : </b></span>"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 40, 80);
  gtk_widget_set_size_request (label15, 80, 48);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  label10 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label10);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label10);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed4), entry3, 768, 176);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed4), entry4, 768, 248);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  spinbutton3_adj = gtk_adjustment_new (1, 1, 50, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton3, 808, 328);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  spinbutton4_adj = gtk_adjustment_new (1, 200, 1200, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton4, 808, 384);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  image12 = create_pixmap (gestion, "rrom.jpg");
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed4), image12, 0, 0);
  gtk_widget_set_size_request (image12, 1008, 600);

  label49 = gtk_label_new (_("<span foreground=\"red\"><b>Selectionner un hotel !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label49, 0, 24);
  gtk_widget_set_size_request (label49, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolledwindow1, 0, 88);
  gtk_widget_set_size_request (scrolledwindow1, 584, 384);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_widget_set_size_request (treeview1, 584, 384);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed4), button6, 328, 496);
  gtk_widget_set_size_request (button6, 104, 56);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox6), label32, FALSE, FALSE, 0);

  label48 = gtk_label_new ("");
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed4), label48, 752, 56);
  gtk_widget_set_size_request (label48, 104, 48);

  label25 = gtk_label_new (_("<span foreground=\"white\"><b>Modifier l'Hotel :  </b></span>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 624, 56);
  gtk_widget_set_size_request (label25, 152, 48);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox2, 768, 112);
  gtk_widget_set_size_request (combobox2, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Simple"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Double"));

  label26 = gtk_label_new (_("<span foreground=\"white\"><b>Type de chambre : </b></span>"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed4), label26, 632, 104);
  gtk_widget_set_size_request (label26, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  label27 = gtk_label_new (_("<span foreground=\"white\"><b>Date d'admission :  </b></span>"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed4), label27, 624, 168);
  gtk_widget_set_size_request (label27, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  label28 = gtk_label_new (_("<span foreground=\"white\"><b>Date de sortie :   </b></span>"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed4), label28, 616, 240);
  gtk_widget_set_size_request (label28, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  label29 = gtk_label_new (_("<span foreground=\"white\"><b>Nombre de chambre :   </b></span>"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed4), label29, 624, 320);
  gtk_widget_set_size_request (label29, 144, 48);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  label30 = gtk_label_new (_("<span foreground=\"white\"><b>Prix :    </b></span>"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed4), label30, 616, 384);
  gtk_widget_set_size_request (label30, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  label50 = gtk_label_new (_("<span foreground=\"blue\"><b><i>Hotel modifi\303\251 avec succ\303\251s</i></b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label50, 624, 0);
  gtk_widget_set_size_request (label50, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label50), TRUE);

  Modifier = gtk_button_new ();
  gtk_widget_show (Modifier);
  gtk_fixed_put (GTK_FIXED (fixed4), Modifier, 776, 464);
  gtk_widget_set_size_request (Modifier, 104, 64);

  alignment35 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment35);
  gtk_container_add (GTK_CONTAINER (Modifier), alignment35);

  hbox35 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox35);
  gtk_container_add (GTK_CONTAINER (alignment35), hbox35);

  image64 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image64);
  gtk_box_pack_start (GTK_BOX (hbox35), image64, FALSE, FALSE, 0);

  label264 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label264);
  gtk_box_pack_start (GTK_BOX (hbox35), label264, FALSE, FALSE, 0);

  label11 = gtk_label_new (_("Afficher/Supprimer/Modifier"));
  gtk_widget_show (label11);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label11);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  spinbutton5_adj = gtk_adjustment_new (1, 1, 50, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton5, 336, 472);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  image13 = create_pixmap (gestion, "rsz_apartment-bed-bedroom-comfort-545034.jpg");
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed6), image13, 0, 0);
  gtk_widget_set_size_request (image13, 1008, 600);

  label53 = gtk_label_new (_("<span foreground=\"blue\"><i>Reservation reussite</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), label53, 0, 0);
  gtk_widget_set_size_request (label53, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label53), TRUE);

  label33 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed6), label33, 88, 64);
  gtk_widget_set_size_request (label33, 80, 48);

  label34 = gtk_label_new (_("Type de chambre : "));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed6), label34, 72, 120);
  gtk_widget_set_size_request (label34, 128, 48);

  label40 = gtk_label_new ("");
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed6), label40, 416, 120);
  gtk_widget_set_size_request (label40, 128, 48);

  label35 = gtk_label_new (_("Date d'admission : "));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed6), label35, 72, 192);
  gtk_widget_set_size_request (label35, 128, 48);

  label41 = gtk_label_new ("");
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed6), label41, 440, 192);
  gtk_widget_set_size_request (label41, 128, 48);

  label36 = gtk_label_new (_("Date de sortie : "));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed6), label36, 72, 264);
  gtk_widget_set_size_request (label36, 128, 48);

  label42 = gtk_label_new ("");
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed6), label42, 440, 264);
  gtk_widget_set_size_request (label42, 128, 48);

  label37 = gtk_label_new (_("Nombre de chambre disponible : "));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed6), label37, 32, 328);
  gtk_widget_set_size_request (label37, 240, 64);

  label43 = gtk_label_new ("");
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed6), label43, 416, 328);
  gtk_widget_set_size_request (label43, 240, 64);

  label38 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed6), label38, 80, 408);
  gtk_widget_set_size_request (label38, 128, 48);

  label44 = gtk_label_new ("");
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed6), label44, 440, 408);
  gtk_widget_set_size_request (label44, 128, 48);

  label46 = gtk_label_new (_("Nombre de chambre : "));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed6), label46, 96, 464);
  gtk_widget_set_size_request (label46, 144, 48);

  label52 = gtk_label_new (_("<span foreground=\"red\"><b>Nombre de chambre invalide !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), label52, 408, 448);
  gtk_widget_set_size_request (label52, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label52), TRUE);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed6), button7, 360, 544);
  gtk_widget_set_size_request (button7, 96, 53);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button7), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox7), label47, FALSE, FALSE, 0);

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed6), combobox3, 184, 72);
  gtk_widget_set_size_request (combobox3, 160, 32);

  label13 = gtk_label_new (_("Reserver"));
  gtk_widget_show (label13);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label13);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed7), entry5, 816, 160);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  image14 = create_pixmap (gestion, "adventure-city-country-destination-240834 (1).jpg");
  gtk_widget_show (image14);
  gtk_fixed_put (GTK_FIXED (fixed7), image14, 0, 0);
  gtk_widget_set_size_request (image14, 1016, 600);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed7), button8, 832, 200);
  gtk_widget_set_size_request (button8, 96, 53);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button8), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox8), label59, FALSE, FALSE, 0);

  label57 = gtk_label_new ("");
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed7), label57, 792, 344);
  gtk_widget_set_size_request (label57, 72, 56);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed7), scrolledwindow2, 16, 56);
  gtk_widget_set_size_request (scrolledwindow2, 592, 344);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview2);
  gtk_widget_set_size_request (treeview2, 592, 344);

  label56 = gtk_label_new (_("<span foreground=\"red\"><b>Saisir type de chambre !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed7), label56, 696, 72);
  gtk_widget_set_size_request (label56, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label56), TRUE);

  label55 = gtk_label_new (_("<span foreground=\"white\"><b>Type de chambre : </b></span>"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed7), label55, 664, 152);
  gtk_widget_set_size_request (label55, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label55), TRUE);

  label58 = gtk_label_new (_("<span foreground=\"black\"><b>Resulta(s) trouv\303\251e(s)</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed7), label58, 792, 336);
  gtk_widget_set_size_request (label58, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label58), TRUE);

  label54 = gtk_label_new (_("Chercher"));
  gtk_widget_show (label54);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label54);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_gestionAcceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_Ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_Supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) Modifier, "clicked",
                    G_CALLBACK (on_Modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_ReserverHotel_clicked),
                    NULL);
  g_signal_connect ((gpointer) combobox3, "changed",
                    G_CALLBACK (on_combobox3_changed),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_ChercherHotel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion, gestion, "gestion");
  GLADE_HOOKUP_OBJECT (gestion, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (gestion, image11, "image11");
  GLADE_HOOKUP_OBJECT (gestion, button2, "button2");
  GLADE_HOOKUP_OBJECT (gestion, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (gestion, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (gestion, image2, "image2");
  GLADE_HOOKUP_OBJECT (gestion, label2, "label2");
  GLADE_HOOKUP_OBJECT (gestion, button12, "button12");
  GLADE_HOOKUP_OBJECT (gestion, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (gestion, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (gestion, image20, "image20");
  GLADE_HOOKUP_OBJECT (gestion, label71, "label71");
  GLADE_HOOKUP_OBJECT (gestion, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (gestion, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (gestion, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (gestion, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (gestion, calendar2, "calendar2");
  GLADE_HOOKUP_OBJECT (gestion, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (gestion, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (gestion, image10, "image10");
  GLADE_HOOKUP_OBJECT (gestion, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (gestion, label18, "label18");
  GLADE_HOOKUP_OBJECT (gestion, label16, "label16");
  GLADE_HOOKUP_OBJECT (gestion, label17, "label17");
  GLADE_HOOKUP_OBJECT (gestion, label19, "label19");
  GLADE_HOOKUP_OBJECT (gestion, label20, "label20");
  GLADE_HOOKUP_OBJECT (gestion, button4, "button4");
  GLADE_HOOKUP_OBJECT (gestion, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion, label21, "label21");
  GLADE_HOOKUP_OBJECT (gestion, label51, "label51");
  GLADE_HOOKUP_OBJECT (gestion, label23, "label23");
  GLADE_HOOKUP_OBJECT (gestion, label22, "label22");
  GLADE_HOOKUP_OBJECT (gestion, label14, "label14");
  GLADE_HOOKUP_OBJECT (gestion, label15, "label15");
  GLADE_HOOKUP_OBJECT (gestion, label10, "label10");
  GLADE_HOOKUP_OBJECT (gestion, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (gestion, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (gestion, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (gestion, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (gestion, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (gestion, image12, "image12");
  GLADE_HOOKUP_OBJECT (gestion, label49, "label49");
  GLADE_HOOKUP_OBJECT (gestion, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (gestion, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (gestion, button6, "button6");
  GLADE_HOOKUP_OBJECT (gestion, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestion, label32, "label32");
  GLADE_HOOKUP_OBJECT (gestion, label48, "label48");
  GLADE_HOOKUP_OBJECT (gestion, label25, "label25");
  GLADE_HOOKUP_OBJECT (gestion, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (gestion, label26, "label26");
  GLADE_HOOKUP_OBJECT (gestion, label27, "label27");
  GLADE_HOOKUP_OBJECT (gestion, label28, "label28");
  GLADE_HOOKUP_OBJECT (gestion, label29, "label29");
  GLADE_HOOKUP_OBJECT (gestion, label30, "label30");
  GLADE_HOOKUP_OBJECT (gestion, label50, "label50");
  GLADE_HOOKUP_OBJECT (gestion, Modifier, "Modifier");
  GLADE_HOOKUP_OBJECT (gestion, alignment35, "alignment35");
  GLADE_HOOKUP_OBJECT (gestion, hbox35, "hbox35");
  GLADE_HOOKUP_OBJECT (gestion, image64, "image64");
  GLADE_HOOKUP_OBJECT (gestion, label264, "label264");
  GLADE_HOOKUP_OBJECT (gestion, label11, "label11");
  GLADE_HOOKUP_OBJECT (gestion, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (gestion, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (gestion, image13, "image13");
  GLADE_HOOKUP_OBJECT (gestion, label53, "label53");
  GLADE_HOOKUP_OBJECT (gestion, label33, "label33");
  GLADE_HOOKUP_OBJECT (gestion, label34, "label34");
  GLADE_HOOKUP_OBJECT (gestion, label40, "label40");
  GLADE_HOOKUP_OBJECT (gestion, label35, "label35");
  GLADE_HOOKUP_OBJECT (gestion, label41, "label41");
  GLADE_HOOKUP_OBJECT (gestion, label36, "label36");
  GLADE_HOOKUP_OBJECT (gestion, label42, "label42");
  GLADE_HOOKUP_OBJECT (gestion, label37, "label37");
  GLADE_HOOKUP_OBJECT (gestion, label43, "label43");
  GLADE_HOOKUP_OBJECT (gestion, label38, "label38");
  GLADE_HOOKUP_OBJECT (gestion, label44, "label44");
  GLADE_HOOKUP_OBJECT (gestion, label46, "label46");
  GLADE_HOOKUP_OBJECT (gestion, label52, "label52");
  GLADE_HOOKUP_OBJECT (gestion, button7, "button7");
  GLADE_HOOKUP_OBJECT (gestion, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (gestion, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (gestion, image7, "image7");
  GLADE_HOOKUP_OBJECT (gestion, label47, "label47");
  GLADE_HOOKUP_OBJECT (gestion, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (gestion, label13, "label13");
  GLADE_HOOKUP_OBJECT (gestion, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (gestion, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (gestion, image14, "image14");
  GLADE_HOOKUP_OBJECT (gestion, button8, "button8");
  GLADE_HOOKUP_OBJECT (gestion, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (gestion, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (gestion, image8, "image8");
  GLADE_HOOKUP_OBJECT (gestion, label59, "label59");
  GLADE_HOOKUP_OBJECT (gestion, label57, "label57");
  GLADE_HOOKUP_OBJECT (gestion, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (gestion, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (gestion, label56, "label56");
  GLADE_HOOKUP_OBJECT (gestion, label55, "label55");
  GLADE_HOOKUP_OBJECT (gestion, label58, "label58");
  GLADE_HOOKUP_OBJECT (gestion, label54, "label54");

  return gestion;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed8;
  GtkWidget *image15;
  GtkWidget *buttonAgent;
  GtkWidget *button38;
  GtkWidget *button41;
  GtkWidget *alignment38;
  GtkWidget *hbox38;
  GtkWidget *image68;
  GtkWidget *label267;
  GtkWidget *button42;
  GtkWidget *image69;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));
  gtk_window_set_resizable (GTK_WINDOW (window1), FALSE);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (window1), fixed8);

  image15 = create_pixmap (window1, "camera.jpg");
  gtk_widget_show (image15);
  gtk_fixed_put (GTK_FIXED (fixed8), image15, 0, 0);
  gtk_widget_set_size_request (image15, 1000, 704);

  buttonAgent = gtk_button_new_with_mnemonic (_("Agent "));
  gtk_widget_show (buttonAgent);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonAgent, 384, 168);
  gtk_widget_set_size_request (buttonAgent, 250, 150);

  button38 = gtk_button_new_with_mnemonic (_("Client"));
  gtk_widget_show (button38);
  gtk_fixed_put (GTK_FIXED (fixed8), button38, 384, 376);
  gtk_widget_set_size_request (button38, 250, 150);

  button41 = gtk_button_new ();
  gtk_widget_show (button41);
  gtk_fixed_put (GTK_FIXED (fixed8), button41, 112, 600);
  gtk_widget_set_size_request (button41, 136, 72);

  alignment38 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment38);
  gtk_container_add (GTK_CONTAINER (button41), alignment38);

  hbox38 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox38);
  gtk_container_add (GTK_CONTAINER (alignment38), hbox38);

  image68 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image68);
  gtk_box_pack_start (GTK_BOX (hbox38), image68, FALSE, FALSE, 0);

  label267 = gtk_label_new_with_mnemonic (_("Retour "));
  gtk_widget_show (label267);
  gtk_box_pack_start (GTK_BOX (hbox38), label267, FALSE, FALSE, 0);

  button42 = gtk_button_new ();
  gtk_widget_show (button42);
  gtk_fixed_put (GTK_FIXED (fixed8), button42, 952, 0);
  gtk_widget_set_size_request (button42, 48, 56);

  image69 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image69);
  gtk_container_add (GTK_CONTAINER (button42), image69);

  g_signal_connect ((gpointer) buttonAgent, "clicked",
                    G_CALLBACK (on_buttonAgent_clicked),
                    NULL);
  g_signal_connect ((gpointer) button38, "clicked",
                    G_CALLBACK (on_button38_clicked),
                    NULL);
  g_signal_connect ((gpointer) button41, "clicked",
                    G_CALLBACK (on_button41_clicked),
                    NULL);
  g_signal_connect ((gpointer) button42, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window1, image15, "image15");
  GLADE_HOOKUP_OBJECT (window1, buttonAgent, "buttonAgent");
  GLADE_HOOKUP_OBJECT (window1, button38, "button38");
  GLADE_HOOKUP_OBJECT (window1, button41, "button41");
  GLADE_HOOKUP_OBJECT (window1, alignment38, "alignment38");
  GLADE_HOOKUP_OBJECT (window1, hbox38, "hbox38");
  GLADE_HOOKUP_OBJECT (window1, image68, "image68");
  GLADE_HOOKUP_OBJECT (window1, label267, "label267");
  GLADE_HOOKUP_OBJECT (window1, button42, "button42");
  GLADE_HOOKUP_OBJECT (window1, image69, "image69");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed9;
  GtkWidget *label73;
  GtkWidget *label74;
  GtkWidget *label75;
  GtkWidget *label76;
  GtkWidget *label77;
  GtkWidget *fixed10;
  GtkWidget *notebook2;
  GtkWidget *fixed22;
  GtkWidget *image57;
  GtkWidget *scrolledwindow5;
  GtkWidget *treeview5;
  GtkWidget *label230;
  GtkWidget *button35;
  GtkWidget *alignment34;
  GtkWidget *hbox34;
  GtkWidget *image63;
  GtkWidget *label262;
  GtkWidget *label228;
  GtkWidget *label239;
  GtkWidget *fixed23;
  GtkWidget *image60;
  GtkWidget *label241;
  GtkWidget *label242;
  GtkWidget *label243;
  GtkWidget *label244;
  GtkWidget *label245;
  GtkWidget *label246;
  GtkWidget *label247;
  GtkWidget *label248;
  GtkWidget *label249;
  GtkWidget *label250;
  GtkWidget *label251;
  GtkWidget *label252;
  GtkWidget *button34;
  GtkWidget *alignment33;
  GtkWidget *hbox33;
  GtkWidget *image61;
  GtkWidget *label254;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *label240;
  GtkWidget *label253;
  GtkWidget *label255;
  GtkWidget *image65;
  GtkWidget *button40;
  GtkWidget *alignment37;
  GtkWidget *hbox37;
  GtkWidget *image67;
  GtkWidget *label266;
  GtkWidget *button39;
  GtkWidget *alignment36;
  GtkWidget *hbox36;
  GtkWidget *image66;
  GtkWidget *label265;
  GtkWidget *label268;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));
  gtk_window_set_resizable (GTK_WINDOW (window2), FALSE);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (window2), fixed9);

  label73 = gtk_label_new ("");
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed9), label73, 200, 168);
  gtk_widget_set_size_request (label73, 176, 64);

  label74 = gtk_label_new ("");
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed9), label74, 240, 232);
  gtk_widget_set_size_request (label74, 160, 64);

  label75 = gtk_label_new ("");
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed9), label75, 240, 296);
  gtk_widget_set_size_request (label75, 160, 72);

  label76 = gtk_label_new ("");
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed9), label76, 312, 400);
  gtk_widget_set_size_request (label76, 184, 72);

  label77 = gtk_label_new ("");
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed9), label77, 200, 480);
  gtk_widget_set_size_request (label77, 176, 80);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_fixed_put (GTK_FIXED (fixed9), fixed10, 0, 0);
  gtk_widget_set_size_request (fixed10, 0, 0);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_fixed_put (GTK_FIXED (fixed9), notebook2, 0, 0);
  gtk_widget_set_size_request (notebook2, 1008, 632);

  fixed22 = gtk_fixed_new ();
  gtk_widget_show (fixed22);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed22);

  image57 = create_pixmap (window2, "rrom.jpg");
  gtk_widget_show (image57);
  gtk_fixed_put (GTK_FIXED (fixed22), image57, 0, 0);
  gtk_widget_set_size_request (image57, 1008, 600);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_fixed_put (GTK_FIXED (fixed22), scrolledwindow5, 0, 88);
  gtk_widget_set_size_request (scrolledwindow5, 584, 384);

  treeview5 = gtk_tree_view_new ();
  gtk_widget_show (treeview5);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), treeview5);
  gtk_widget_set_size_request (treeview5, 584, 384);

  label230 = gtk_label_new ("");
  gtk_widget_show (label230);
  gtk_fixed_put (GTK_FIXED (fixed22), label230, 752, 56);
  gtk_widget_set_size_request (label230, 104, 48);

  button35 = gtk_button_new ();
  gtk_widget_show (button35);
  gtk_fixed_put (GTK_FIXED (fixed22), button35, 792, 504);
  gtk_widget_set_size_request (button35, 150, 68);

  alignment34 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment34);
  gtk_container_add (GTK_CONTAINER (button35), alignment34);

  hbox34 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox34);
  gtk_container_add (GTK_CONTAINER (alignment34), hbox34);

  image63 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image63);
  gtk_box_pack_start (GTK_BOX (hbox34), image63, FALSE, FALSE, 0);

  label262 = gtk_label_new_with_mnemonic (_("Reserver "));
  gtk_widget_show (label262);
  gtk_box_pack_start (GTK_BOX (hbox34), label262, FALSE, FALSE, 0);

  label228 = gtk_label_new (_("<span foreground=\"red\"><b>Selectionner un hotel !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed22), label228, 0, 24);
  gtk_widget_set_size_request (label228, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label228), TRUE);

  label239 = gtk_label_new (_("Afficher"));
  gtk_widget_show (label239);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label239);

  fixed23 = gtk_fixed_new ();
  gtk_widget_show (fixed23);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed23);

  image60 = create_pixmap (window2, "rsz_apartment-bed-bedroom-comfort-545034.jpg");
  gtk_widget_show (image60);
  gtk_fixed_put (GTK_FIXED (fixed23), image60, 0, 0);
  gtk_widget_set_size_request (image60, 1008, 600);

  label241 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label241);
  gtk_fixed_put (GTK_FIXED (fixed23), label241, 88, 64);
  gtk_widget_set_size_request (label241, 80, 48);

  label242 = gtk_label_new (_("Type de chambre : "));
  gtk_widget_show (label242);
  gtk_fixed_put (GTK_FIXED (fixed23), label242, 72, 120);
  gtk_widget_set_size_request (label242, 128, 48);

  label243 = gtk_label_new ("");
  gtk_widget_show (label243);
  gtk_fixed_put (GTK_FIXED (fixed23), label243, 416, 120);
  gtk_widget_set_size_request (label243, 128, 48);

  label244 = gtk_label_new (_("Date d'admission : "));
  gtk_widget_show (label244);
  gtk_fixed_put (GTK_FIXED (fixed23), label244, 72, 192);
  gtk_widget_set_size_request (label244, 128, 48);

  label245 = gtk_label_new ("");
  gtk_widget_show (label245);
  gtk_fixed_put (GTK_FIXED (fixed23), label245, 440, 192);
  gtk_widget_set_size_request (label245, 128, 48);

  label246 = gtk_label_new (_("Date de sortie : "));
  gtk_widget_show (label246);
  gtk_fixed_put (GTK_FIXED (fixed23), label246, 72, 264);
  gtk_widget_set_size_request (label246, 128, 48);

  label247 = gtk_label_new ("");
  gtk_widget_show (label247);
  gtk_fixed_put (GTK_FIXED (fixed23), label247, 440, 264);
  gtk_widget_set_size_request (label247, 128, 48);

  label248 = gtk_label_new (_("Nombre de chambre disponible : "));
  gtk_widget_show (label248);
  gtk_fixed_put (GTK_FIXED (fixed23), label248, 32, 328);
  gtk_widget_set_size_request (label248, 240, 64);

  label249 = gtk_label_new ("");
  gtk_widget_show (label249);
  gtk_fixed_put (GTK_FIXED (fixed23), label249, 416, 328);
  gtk_widget_set_size_request (label249, 240, 64);

  label250 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label250);
  gtk_fixed_put (GTK_FIXED (fixed23), label250, 80, 408);
  gtk_widget_set_size_request (label250, 128, 48);

  label251 = gtk_label_new ("");
  gtk_widget_show (label251);
  gtk_fixed_put (GTK_FIXED (fixed23), label251, 440, 408);
  gtk_widget_set_size_request (label251, 128, 48);

  label252 = gtk_label_new (_("Nombre de chambre : "));
  gtk_widget_show (label252);
  gtk_fixed_put (GTK_FIXED (fixed23), label252, 96, 464);
  gtk_widget_set_size_request (label252, 144, 48);

  button34 = gtk_button_new ();
  gtk_widget_show (button34);
  gtk_fixed_put (GTK_FIXED (fixed23), button34, 360, 544);
  gtk_widget_set_size_request (button34, 96, 53);

  alignment33 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (button34), alignment33);

  hbox33 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox33);
  gtk_container_add (GTK_CONTAINER (alignment33), hbox33);

  image61 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image61);
  gtk_box_pack_start (GTK_BOX (hbox33), image61, FALSE, FALSE, 0);

  label254 = gtk_label_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (label254);
  gtk_box_pack_start (GTK_BOX (hbox33), label254, FALSE, FALSE, 0);

  spinbutton6_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed23), spinbutton6, 296, 472);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  label240 = gtk_label_new (_("<span foreground=\"blue\"><i>Reservation reussite</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed23), label240, 0, 0);
  gtk_widget_set_size_request (label240, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label240), TRUE);

  label253 = gtk_label_new (_("<span foreground=\"red\"><b>Nombre de chambre invalide !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed23), label253, 408, 448);
  gtk_widget_set_size_request (label253, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label253), TRUE);

  label255 = gtk_label_new (_("Reserver"));
  gtk_widget_show (label255);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label255);

  image65 = create_pixmap (window2, "brown-close-up-hd-wallpaper-surface-172289.jpg");
  gtk_widget_show (image65);
  gtk_fixed_put (GTK_FIXED (fixed9), image65, 0, 632);
  gtk_widget_set_size_request (image65, 1008, 112);

  button40 = gtk_button_new ();
  gtk_widget_show (button40);
  gtk_fixed_put (GTK_FIXED (fixed9), button40, 816, 640);
  gtk_widget_set_size_request (button40, 150, 68);

  alignment37 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment37);
  gtk_container_add (GTK_CONTAINER (button40), alignment37);

  hbox37 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox37);
  gtk_container_add (GTK_CONTAINER (alignment37), hbox37);

  image67 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image67);
  gtk_box_pack_start (GTK_BOX (hbox37), image67, FALSE, FALSE, 0);

  label266 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label266);
  gtk_box_pack_start (GTK_BOX (hbox37), label266, FALSE, FALSE, 0);

  button39 = gtk_button_new ();
  gtk_widget_show (button39);
  gtk_fixed_put (GTK_FIXED (fixed9), button39, 32, 648);
  gtk_widget_set_size_request (button39, 150, 68);

  alignment36 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment36);
  gtk_container_add (GTK_CONTAINER (button39), alignment36);

  hbox36 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox36);
  gtk_container_add (GTK_CONTAINER (alignment36), hbox36);

  image66 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image66);
  gtk_box_pack_start (GTK_BOX (hbox36), image66, FALSE, FALSE, 0);

  label265 = gtk_label_new_with_mnemonic (_("Retour "));
  gtk_widget_show (label265);
  gtk_box_pack_start (GTK_BOX (hbox36), label265, FALSE, FALSE, 0);

  label268 = gtk_label_new ("");
  gtk_widget_show (label268);
  gtk_fixed_put (GTK_FIXED (fixed9), label268, 296, 64);
  gtk_widget_set_size_request (label268, 152, 80);

  g_signal_connect ((gpointer) treeview5, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button35, "clicked",
                    G_CALLBACK (on_button35_clicked),
                    NULL);
  g_signal_connect ((gpointer) button34, "clicked",
                    G_CALLBACK (on_button34_clicked),
                    NULL);
  g_signal_connect ((gpointer) button40, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button39, "clicked",
                    G_CALLBACK (on_button39_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window2, label73, "label73");
  GLADE_HOOKUP_OBJECT (window2, label74, "label74");
  GLADE_HOOKUP_OBJECT (window2, label75, "label75");
  GLADE_HOOKUP_OBJECT (window2, label76, "label76");
  GLADE_HOOKUP_OBJECT (window2, label77, "label77");
  GLADE_HOOKUP_OBJECT (window2, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window2, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (window2, fixed22, "fixed22");
  GLADE_HOOKUP_OBJECT (window2, image57, "image57");
  GLADE_HOOKUP_OBJECT (window2, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (window2, treeview5, "treeview5");
  GLADE_HOOKUP_OBJECT (window2, label230, "label230");
  GLADE_HOOKUP_OBJECT (window2, button35, "button35");
  GLADE_HOOKUP_OBJECT (window2, alignment34, "alignment34");
  GLADE_HOOKUP_OBJECT (window2, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (window2, image63, "image63");
  GLADE_HOOKUP_OBJECT (window2, label262, "label262");
  GLADE_HOOKUP_OBJECT (window2, label228, "label228");
  GLADE_HOOKUP_OBJECT (window2, label239, "label239");
  GLADE_HOOKUP_OBJECT (window2, fixed23, "fixed23");
  GLADE_HOOKUP_OBJECT (window2, image60, "image60");
  GLADE_HOOKUP_OBJECT (window2, label241, "label241");
  GLADE_HOOKUP_OBJECT (window2, label242, "label242");
  GLADE_HOOKUP_OBJECT (window2, label243, "label243");
  GLADE_HOOKUP_OBJECT (window2, label244, "label244");
  GLADE_HOOKUP_OBJECT (window2, label245, "label245");
  GLADE_HOOKUP_OBJECT (window2, label246, "label246");
  GLADE_HOOKUP_OBJECT (window2, label247, "label247");
  GLADE_HOOKUP_OBJECT (window2, label248, "label248");
  GLADE_HOOKUP_OBJECT (window2, label249, "label249");
  GLADE_HOOKUP_OBJECT (window2, label250, "label250");
  GLADE_HOOKUP_OBJECT (window2, label251, "label251");
  GLADE_HOOKUP_OBJECT (window2, label252, "label252");
  GLADE_HOOKUP_OBJECT (window2, button34, "button34");
  GLADE_HOOKUP_OBJECT (window2, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (window2, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (window2, image61, "image61");
  GLADE_HOOKUP_OBJECT (window2, label254, "label254");
  GLADE_HOOKUP_OBJECT (window2, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (window2, label240, "label240");
  GLADE_HOOKUP_OBJECT (window2, label253, "label253");
  GLADE_HOOKUP_OBJECT (window2, label255, "label255");
  GLADE_HOOKUP_OBJECT (window2, image65, "image65");
  GLADE_HOOKUP_OBJECT (window2, button40, "button40");
  GLADE_HOOKUP_OBJECT (window2, alignment37, "alignment37");
  GLADE_HOOKUP_OBJECT (window2, hbox37, "hbox37");
  GLADE_HOOKUP_OBJECT (window2, image67, "image67");
  GLADE_HOOKUP_OBJECT (window2, label266, "label266");
  GLADE_HOOKUP_OBJECT (window2, button39, "button39");
  GLADE_HOOKUP_OBJECT (window2, alignment36, "alignment36");
  GLADE_HOOKUP_OBJECT (window2, hbox36, "hbox36");
  GLADE_HOOKUP_OBJECT (window2, image66, "image66");
  GLADE_HOOKUP_OBJECT (window2, label265, "label265");
  GLADE_HOOKUP_OBJECT (window2, label268, "label268");

  return window2;
}

