/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window33 (void);
GtkWidget* create_window34 (void);
GtkWidget* create_window35 (void);
GtkWidget* create_window36 (void);
GtkWidget* create_window37 (void);
GtkWidget* create_window38 (void);
