/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Acceuil (void);
GtkWidget* create_gestion_voiture (void);
GtkWidget* create_window1 (void);
GtkWidget* create_window2 (void);
