/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Acceuil (void)
{
  GtkWidget *Acceuil;
  GtkWidget *fixed1;
  GtkWidget *button1d;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;

  Acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Acceuil, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (Acceuil), _("acceuil"));
  gtk_window_set_position (GTK_WINDOW (Acceuil), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (Acceuil), FALSE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Acceuil), fixed1);

  button1d = gtk_button_new ();
  gtk_widget_show (button1d);
  gtk_fixed_put (GTK_FIXED (fixed1), button1d, 400, 336);
  gtk_widget_set_size_request (button1d, 168, 72);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1d), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Gestion des voitures"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button1d, "clicked",
                    G_CALLBACK (on_button1d_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Acceuil, Acceuil, "Acceuil");
  GLADE_HOOKUP_OBJECT (Acceuil, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Acceuil, button1d, "button1d");
  GLADE_HOOKUP_OBJECT (Acceuil, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Acceuil, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Acceuil, image1, "image1");
  GLADE_HOOKUP_OBJECT (Acceuil, label1, "label1");

  return Acceuil;
}

GtkWidget*
create_gestion_voiture (void)
{
  GtkWidget *gestion_voiture;
  GtkWidget *fixed2;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkWidget *entry1d;
  GtkWidget *calendar1d;
  GtkWidget *calendar2d;
  GtkObject *spinbutton2d_adj;
  GtkWidget *spinbutton2d;
  GtkWidget *entry4d;
  GtkWidget *label7;
  GtkWidget *label6;
  GtkWidget *label4;
  GtkWidget *label63;
  GtkWidget *label17;
  GtkObject *spinbutton6d_adj;
  GtkWidget *spinbutton6d;
  GtkWidget *label79;
  GtkWidget *label60;
  GtkWidget *combobox7d;
  GtkWidget *button4d;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label18;
  GtkWidget *label9d;
  GtkWidget *label10d;
  GtkWidget *label61d;
  GtkWidget *label11d;
  GtkWidget *label64d;
  GtkWidget *label19;
  GtkWidget *fixed4;
  GtkObject *spinbutton5d_adj;
  GtkWidget *spinbutton5d;
  GtkWidget *label76;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1d;
  GtkWidget *button5d;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label20;
  GtkWidget *button8d;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label69;
  GtkWidget *button6d;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label29;
  GtkWidget *label77d;
  GtkWidget *label81d;
  GtkWidget *label78d;
  GtkWidget *label34;
  GtkWidget *fixed5;
  GtkWidget *entry2d;
  GtkWidget *entry3d;
  GtkObject *spinbutton4d_adj;
  GtkWidget *spinbutton4d;
  GtkWidget *entry5d;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label67;
  GtkWidget *label65;
  GtkWidget *label25;
  GtkWidget *label24;
  GtkObject *spinbutton7d_adj;
  GtkWidget *spinbutton7d;
  GtkWidget *label80;
  GtkWidget *label30;
  GtkWidget *combobox8d;
  GtkWidget *button7d;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label68d;
  GtkWidget *label33d;
  GtkWidget *label62;
  GtkWidget *fixed6;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview2d;
  GtkWidget *entry6d;
  GtkWidget *label71;
  GtkWidget *button9d;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label75;
  GtkWidget *label72d;
  GtkWidget *label73d;
  GtkWidget *label74d;
  GtkWidget *label70;
  GtkWidget *button2d;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *button3d;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;

  gestion_voiture = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gestion_voiture, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (gestion_voiture), _("Gestion Voitures"));
  gtk_window_set_position (GTK_WINDOW (gestion_voiture), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (gestion_voiture), FALSE);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (gestion_voiture), fixed2);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 1008, 640);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  entry1d = gtk_entry_new ();
  gtk_widget_show (entry1d);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1d, 264, 136);
  gtk_widget_set_size_request (entry1d, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1d), 8226);

  calendar1d = gtk_calendar_new ();
  gtk_widget_show (calendar1d);
  gtk_fixed_put (GTK_FIXED (fixed3), calendar1d, 240, 248);
  gtk_widget_set_size_request (calendar1d, 236, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1d),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  calendar2d = gtk_calendar_new ();
  gtk_widget_show (calendar2d);
  gtk_fixed_put (GTK_FIXED (fixed3), calendar2d, 712, 248);
  gtk_widget_set_size_request (calendar2d, 236, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar2d),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  spinbutton2d_adj = gtk_adjustment_new (1, 200, 1200, 1, 10, 10);
  spinbutton2d = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2d_adj), 1, 0);
  gtk_widget_show (spinbutton2d);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton2d, 256, 472);
  gtk_widget_set_size_request (spinbutton2d, 56, 27);

  entry4d = gtk_entry_new ();
  gtk_widget_show (entry4d);
  gtk_fixed_put (GTK_FIXED (fixed3), entry4d, 264, 80);
  gtk_widget_set_size_request (entry4d, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4d), 8226);

  label7 = gtk_label_new (_("Date de retour : "));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed3), label7, 544, 296);
  gtk_widget_set_size_request (label7, 128, 48);

  label6 = gtk_label_new (_("Date de location : "));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed3), label6, 64, 296);
  gtk_widget_set_size_request (label6, 128, 48);

  label4 = gtk_label_new (_("Matricule : "));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed3), label4, 88, 120);
  gtk_widget_set_size_request (label4, 80, 48);

  label63 = gtk_label_new (_("Marque : "));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed3), label63, 88, 184);
  gtk_widget_set_size_request (label63, 80, 48);

  label17 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 64, 456);
  gtk_widget_set_size_request (label17, 128, 56);

  spinbutton6d_adj = gtk_adjustment_new (1, 1, 5, 1, 10, 10);
  spinbutton6d = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6d_adj), 1, 0);
  gtk_widget_show (spinbutton6d);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton6d, 560, 472);
  gtk_widget_set_size_request (spinbutton6d, 56, 27);

  label79 = gtk_label_new (_("Nombre de voitures"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed3), label79, 408, 456);
  gtk_widget_set_size_request (label79, 136, 56);

  label60 = gtk_label_new (_("CIN : "));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed3), label60, 88, 72);
  gtk_widget_set_size_request (label60, 80, 48);

  combobox7d = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7d);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox7d, 264, 192);
  gtk_widget_set_size_request (combobox7d, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7d), _("BMW"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7d), _("Audi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7d), _("Chevrolet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7d), _("Citroen"));

  button4d = gtk_button_new ();
  gtk_widget_show (button4d);
  gtk_fixed_put (GTK_FIXED (fixed3), button4d, 368, 552);
  gtk_widget_set_size_request (button4d, 96, 53);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4d), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox4), label18, FALSE, FALSE, 0);

  label9d = gtk_label_new (_("<span foreground=\"blue\"><i>Voirure ajout\303\251 avec succ\303\251s</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label9d, 40, 0);
  gtk_widget_set_size_request (label9d, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label9d), TRUE);

  label10d = gtk_label_new (_("<span foreground=\"red\"><b>Voiture existe d\303\251ja !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label10d, 320, 0);
  gtk_widget_set_size_request (label10d, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label10d), TRUE);

  label61d = gtk_label_new (_("<span foreground=\"red\"><b>Saisir CIN !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label61d, 440, 56);
  gtk_widget_set_size_request (label61d, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label61d), TRUE);

  label11d = gtk_label_new (_("<span foreground=\"red\"><b>Saisir Matricule!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label11d, 440, 112);
  gtk_widget_set_size_request (label11d, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label11d), TRUE);

  label64d = gtk_label_new (_("<span foreground=\"red\"><b>Choisir Marque!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label64d, 440, 168);
  gtk_widget_set_size_request (label64d, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label64d), TRUE);

  label19 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label19);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label19);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  spinbutton5d_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton5d = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5d_adj), 1, 0);
  gtk_widget_show (spinbutton5d);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton5d, 752, 232);
  gtk_widget_set_size_request (spinbutton5d, 60, 27);

  label76 = gtk_label_new (_("Nombre de voitures"));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed4), label76, 608, 216);
  gtk_widget_set_size_request (label76, 136, 56);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolledwindow1, 0, 88);
  gtk_widget_set_size_request (scrolledwindow1, 584, 384);

  treeview1d = gtk_tree_view_new ();
  gtk_widget_show (treeview1d);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1d);
  gtk_widget_set_size_request (treeview1d, 584, 384);

  button5d = gtk_button_new ();
  gtk_widget_show (button5d);
  gtk_fixed_put (GTK_FIXED (fixed4), button5d, 64, 512);
  gtk_widget_set_size_request (button5d, 104, 56);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5d), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox5), label20, FALSE, FALSE, 0);

  button8d = gtk_button_new ();
  gtk_widget_show (button8d);
  gtk_fixed_put (GTK_FIXED (fixed4), button8d, 728, 320);
  gtk_widget_set_size_request (button8d, 104, 56);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button8d), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label69 = gtk_label_new_with_mnemonic (_("Louer"));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox8), label69, FALSE, FALSE, 0);

  button6d = gtk_button_new ();
  gtk_widget_show (button6d);
  gtk_fixed_put (GTK_FIXED (fixed4), button6d, 224, 512);
  gtk_widget_set_size_request (button6d, 96, 53);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6d), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox6), label29, FALSE, FALSE, 0);

  label77d = gtk_label_new (_("<span foreground=\"red\"><b>Selectionner une Voiture !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label77d, 0, 0);
  gtk_widget_set_size_request (label77d, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label77d), TRUE);

  label81d = gtk_label_new (_("<span foreground=\"blue\"><i>Voiture Lou\303\251e</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label81d, 656, 80);
  gtk_widget_set_size_request (label81d, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label81d), TRUE);

  label78d = gtk_label_new (_("<span foreground=\"red\"><b>Nombre Invalide !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label78d, 800, 200);
  gtk_widget_set_size_request (label78d, 184, 88);
  gtk_label_set_use_markup (GTK_LABEL (label78d), TRUE);

  label34 = gtk_label_new (_("Afficher/Supprimer"));
  gtk_widget_show (label34);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label34);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  entry2d = gtk_entry_new ();
  gtk_widget_show (entry2d);
  gtk_fixed_put (GTK_FIXED (fixed5), entry2d, 352, 256);
  gtk_widget_set_size_request (entry2d, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2d), 8226);

  entry3d = gtk_entry_new ();
  gtk_widget_show (entry3d);
  gtk_fixed_put (GTK_FIXED (fixed5), entry3d, 352, 320);
  gtk_widget_set_size_request (entry3d, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3d), 8226);

  spinbutton4d_adj = gtk_adjustment_new (1, 200, 1200, 1, 10, 10);
  spinbutton4d = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4d_adj), 1, 0);
  gtk_widget_show (spinbutton4d);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton4d, 392, 384);
  gtk_widget_set_size_request (spinbutton4d, 60, 27);

  entry5d = gtk_entry_new ();
  gtk_widget_show (entry5d);
  gtk_fixed_put (GTK_FIXED (fixed5), entry5d, 352, 136);
  gtk_widget_set_size_request (entry5d, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5d), 8226);

  label27 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed5), label27, 200, 376);
  gtk_widget_set_size_request (label27, 128, 48);

  label28 = gtk_label_new (_("Modifier le Voiture : "));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed5), label28, 200, 72);
  gtk_widget_set_size_request (label28, 152, 48);

  label67 = gtk_label_new (_("Cin : "));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed5), label67, 200, 128);
  gtk_widget_set_size_request (label67, 152, 48);

  label65 = gtk_label_new (_("Marque : "));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed5), label65, 224, 184);
  gtk_widget_set_size_request (label65, 128, 48);

  label25 = gtk_label_new (_("Date de retour : "));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed5), label25, 208, 312);
  gtk_widget_set_size_request (label25, 128, 48);

  label24 = gtk_label_new (_("Date de location : "));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed5), label24, 208, 248);
  gtk_widget_set_size_request (label24, 128, 48);

  spinbutton7d_adj = gtk_adjustment_new (1, 1, 5, 1, 10, 10);
  spinbutton7d = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7d_adj), 1, 0);
  gtk_widget_show (spinbutton7d);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton7d, 712, 384);
  gtk_widget_set_size_request (spinbutton7d, 56, 27);

  label80 = gtk_label_new (_("Nombre de voitures"));
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed5), label80, 536, 368);
  gtk_widget_set_size_request (label80, 136, 56);

  label30 = gtk_label_new ("");
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed5), label30, 384, 72);
  gtk_widget_set_size_request (label30, 104, 48);

  combobox8d = gtk_combo_box_new_text ();
  gtk_widget_show (combobox8d);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox8d, 352, 192);
  gtk_widget_set_size_request (combobox8d, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8d), _("BMW"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8d), _("Audi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8d), _("Chevrolet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8d), _("Citroen"));

  button7d = gtk_button_new ();
  gtk_fixed_put (GTK_FIXED (fixed5), button7d, 352, 496);
  gtk_widget_set_size_request (button7d, 96, 53);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button7d), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label68d = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label68d);
  gtk_box_pack_start (GTK_BOX (hbox7), label68d, FALSE, FALSE, 0);

  label33d = gtk_label_new (_("<span foreground=\"blue\"><i>Voiture modifi\303\251e avec succ\303\251s</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed5), label33d, 312, 0);
  gtk_widget_set_size_request (label33d, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label33d), TRUE);

  label62 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label62);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label62);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed6), scrolledwindow2, 0, 48);
  gtk_widget_set_size_request (scrolledwindow2, 592, 344);

  treeview2d = gtk_tree_view_new ();
  gtk_widget_show (treeview2d);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview2d);
  gtk_widget_set_size_request (treeview2d, 592, 344);

  entry6d = gtk_entry_new ();
  gtk_widget_show (entry6d);
  gtk_fixed_put (GTK_FIXED (fixed6), entry6d, 744, 160);
  gtk_widget_set_size_request (entry6d, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6d), 8226);

  label71 = gtk_label_new (_("Marque : "));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed6), label71, 600, 152);
  gtk_widget_set_size_request (label71, 128, 48);

  button9d = gtk_button_new ();
  gtk_widget_show (button9d);
  gtk_fixed_put (GTK_FIXED (fixed6), button9d, 752, 360);
  gtk_widget_set_size_request (button9d, 96, 53);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button9d), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label75 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (hbox9), label75, FALSE, FALSE, 0);

  label72d = gtk_label_new (_("<span foreground=\"red\"><b>Saisir Marque !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), label72d, 656, 72);
  gtk_widget_set_size_request (label72d, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label72d), TRUE);

  label73d = gtk_label_new ("");
  gtk_widget_show (label73d);
  gtk_fixed_put (GTK_FIXED (fixed6), label73d, 688, 224);
  gtk_widget_set_size_request (label73d, 72, 56);

  label74d = gtk_label_new (_("<span foreground=\"green\"><b>Resulta(s) trouv\303\251e(s)</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), label74d, 704, 216);
  gtk_widget_set_size_request (label74d, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label74d), TRUE);

  label70 = gtk_label_new (_("Chercher"));
  gtk_widget_show (label70);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label70);

  button2d = gtk_button_new ();
  gtk_widget_show (button2d);
  gtk_fixed_put (GTK_FIXED (fixed2), button2d, 16, 640);
  gtk_widget_set_size_request (button2d, 96, 53);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2d), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  button3d = gtk_button_new ();
  gtk_widget_show (button3d);
  gtk_fixed_put (GTK_FIXED (fixed2), button3d, 888, 640);
  gtk_widget_set_size_request (button3d, 96, 53);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3d), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button4d, "clicked",
                    G_CALLBACK (on_button4d_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5d, "clicked",
                    G_CALLBACK (on_button5d_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8d, "clicked",
                    G_CALLBACK (on_button8d_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6d, "clicked",
                    G_CALLBACK (on_button6d_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7d, "clicked",
                    G_CALLBACK (on_button7d_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9d, "clicked",
                    G_CALLBACK (on_button9d_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2d, "clicked",
                    G_CALLBACK (on_button2d_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3d, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_voiture, gestion_voiture, "gestion_voiture");
  GLADE_HOOKUP_OBJECT (gestion_voiture, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (gestion_voiture, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (gestion_voiture, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (gestion_voiture, entry1d, "entry1d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, calendar1d, "calendar1d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, calendar2d, "calendar2d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, spinbutton2d, "spinbutton2d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, entry4d, "entry4d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label7, "label7");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label6, "label6");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label4, "label4");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label63, "label63");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label17, "label17");
  GLADE_HOOKUP_OBJECT (gestion_voiture, spinbutton6d, "spinbutton6d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label79, "label79");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label60, "label60");
  GLADE_HOOKUP_OBJECT (gestion_voiture, combobox7d, "combobox7d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, button4d, "button4d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion_voiture, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion_voiture, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label18, "label18");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label9d, "label9d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label10d, "label10d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label61d, "label61d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label11d, "label11d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label64d, "label64d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label19, "label19");
  GLADE_HOOKUP_OBJECT (gestion_voiture, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (gestion_voiture, spinbutton5d, "spinbutton5d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label76, "label76");
  GLADE_HOOKUP_OBJECT (gestion_voiture, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (gestion_voiture, treeview1d, "treeview1d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, button5d, "button5d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestion_voiture, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestion_voiture, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label20, "label20");
  GLADE_HOOKUP_OBJECT (gestion_voiture, button8d, "button8d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (gestion_voiture, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (gestion_voiture, image8, "image8");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label69, "label69");
  GLADE_HOOKUP_OBJECT (gestion_voiture, button6d, "button6d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion_voiture, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion_voiture, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label29, "label29");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label77d, "label77d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label81d, "label81d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label78d, "label78d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label34, "label34");
  GLADE_HOOKUP_OBJECT (gestion_voiture, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (gestion_voiture, entry2d, "entry2d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, entry3d, "entry3d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, spinbutton4d, "spinbutton4d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, entry5d, "entry5d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label27, "label27");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label28, "label28");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label67, "label67");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label65, "label65");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label25, "label25");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label24, "label24");
  GLADE_HOOKUP_OBJECT (gestion_voiture, spinbutton7d, "spinbutton7d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label80, "label80");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label30, "label30");
  GLADE_HOOKUP_OBJECT (gestion_voiture, combobox8d, "combobox8d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, button7d, "button7d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (gestion_voiture, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (gestion_voiture, image7, "image7");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label68d, "label68d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label33d, "label33d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label62, "label62");
  GLADE_HOOKUP_OBJECT (gestion_voiture, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (gestion_voiture, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (gestion_voiture, treeview2d, "treeview2d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, entry6d, "entry6d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label71, "label71");
  GLADE_HOOKUP_OBJECT (gestion_voiture, button9d, "button9d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (gestion_voiture, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (gestion_voiture, image9, "image9");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label75, "label75");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label72d, "label72d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label73d, "label73d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label74d, "label74d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label70, "label70");
  GLADE_HOOKUP_OBJECT (gestion_voiture, button2d, "button2d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (gestion_voiture, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (gestion_voiture, image2, "image2");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label2, "label2");
  GLADE_HOOKUP_OBJECT (gestion_voiture, button3d, "button3d");
  GLADE_HOOKUP_OBJECT (gestion_voiture, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestion_voiture, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestion_voiture, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label3, "label3");

  return gestion_voiture;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed7;
  GtkWidget *button11d;
  GtkWidget *button12d;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label82;
  GtkWidget *button10d;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window1), fixed7);

  button11d = gtk_button_new_with_mnemonic (_("client"));
  gtk_widget_show (button11d);
  gtk_fixed_put (GTK_FIXED (fixed7), button11d, 120, 144);
  gtk_widget_set_size_request (button11d, 128, 69);

  button12d = gtk_button_new ();
  gtk_widget_show (button12d);
  gtk_fixed_put (GTK_FIXED (fixed7), button12d, 40, 256);
  gtk_widget_set_size_request (button12d, 80, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button12d), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label82 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label82);
  gtk_box_pack_start (GTK_BOX (hbox10), label82, FALSE, FALSE, 0);

  button10d = gtk_button_new_with_mnemonic (_("agent "));
  gtk_widget_show (button10d);
  gtk_fixed_put (GTK_FIXED (fixed7), button10d, 120, 48);
  gtk_widget_set_size_request (button10d, 130, 64);

  g_signal_connect ((gpointer) button11d, "clicked",
                    G_CALLBACK (on_button11d_clicked),
                    NULL);
  g_signal_connect ((gpointer) button12d, "clicked",
                    G_CALLBACK (on_button12d_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10d, "clicked",
                    G_CALLBACK (on_button10d_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window1, button11d, "button11d");
  GLADE_HOOKUP_OBJECT (window1, button12d, "button12d");
  GLADE_HOOKUP_OBJECT (window1, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window1, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window1, image10, "image10");
  GLADE_HOOKUP_OBJECT (window1, label82, "label82");
  GLADE_HOOKUP_OBJECT (window1, button10d, "button10d");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed8;
  GtkWidget *notebook2;
  GtkWidget *fixed10;
  GtkObject *spinbutton10d_adj;
  GtkWidget *spinbutton10d;
  GtkWidget *label105;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeview3d;
  GtkWidget *button18d;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label101;
  GtkWidget *label102d;
  GtkWidget *label103d;
  GtkWidget *label104d;
  GtkWidget *label106;
  GtkWidget *button13d;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label83;
  GtkWidget *button14d;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label84;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window2, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (window2), _("Gestion Voitures"));
  gtk_window_set_position (GTK_WINDOW (window2), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (window2), FALSE);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (window2), fixed8);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_fixed_put (GTK_FIXED (fixed8), notebook2, 0, 0);
  gtk_widget_set_size_request (notebook2, 1008, 640);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed10);

  spinbutton10d_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton10d = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton10d_adj), 1, 0);
  gtk_widget_show (spinbutton10d);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton10d, 752, 232);
  gtk_widget_set_size_request (spinbutton10d, 60, 27);

  label105 = gtk_label_new (_("Nombre de voitures"));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed10), label105, 608, 216);
  gtk_widget_set_size_request (label105, 136, 56);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_fixed_put (GTK_FIXED (fixed10), scrolledwindow3, 0, 88);
  gtk_widget_set_size_request (scrolledwindow3, 584, 384);

  treeview3d = gtk_tree_view_new ();
  gtk_widget_show (treeview3d);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeview3d);
  gtk_widget_set_size_request (treeview3d, 584, 384);

  button18d = gtk_button_new ();
  gtk_widget_show (button18d);
  gtk_fixed_put (GTK_FIXED (fixed10), button18d, 728, 320);
  gtk_widget_set_size_request (button18d, 104, 56);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button18d), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label101 = gtk_label_new_with_mnemonic (_("Louer"));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox16), label101, FALSE, FALSE, 0);

  label102d = gtk_label_new (_("<span foreground=\"red\"><b>Selectionner une Voiture !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed10), label102d, 0, 0);
  gtk_widget_set_size_request (label102d, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label102d), TRUE);

  label103d = gtk_label_new (_("<span foreground=\"blue\"><i>Voiture Lou\303\251e</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed10), label103d, 656, 80);
  gtk_widget_set_size_request (label103d, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label103d), TRUE);

  label104d = gtk_label_new (_("<span foreground=\"red\"><b>Nombre Invalide !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed10), label104d, 800, 200);
  gtk_widget_set_size_request (label104d, 184, 88);
  gtk_label_set_use_markup (GTK_LABEL (label104d), TRUE);

  label106 = gtk_label_new (_("Afficher/louer"));
  gtk_widget_show (label106);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label106);

  button13d = gtk_button_new ();
  gtk_widget_show (button13d);
  gtk_fixed_put (GTK_FIXED (fixed8), button13d, 16, 640);
  gtk_widget_set_size_request (button13d, 96, 53);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button13d), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label83 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label83);
  gtk_box_pack_start (GTK_BOX (hbox11), label83, FALSE, FALSE, 0);

  button14d = gtk_button_new ();
  gtk_widget_show (button14d);
  gtk_fixed_put (GTK_FIXED (fixed8), button14d, 888, 640);
  gtk_widget_set_size_request (button14d, 96, 53);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button14d), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label84 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label84);
  gtk_box_pack_start (GTK_BOX (hbox12), label84, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button18d, "clicked",
                    G_CALLBACK (on_button18d_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13d, "clicked",
                    G_CALLBACK (on_button13d_enter),
                    NULL);
  g_signal_connect ((gpointer) button14d, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window2, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (window2, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window2, spinbutton10d, "spinbutton10d");
  GLADE_HOOKUP_OBJECT (window2, label105, "label105");
  GLADE_HOOKUP_OBJECT (window2, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (window2, treeview3d, "treeview3d");
  GLADE_HOOKUP_OBJECT (window2, button18d, "button18d");
  GLADE_HOOKUP_OBJECT (window2, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window2, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window2, image16, "image16");
  GLADE_HOOKUP_OBJECT (window2, label101, "label101");
  GLADE_HOOKUP_OBJECT (window2, label102d, "label102d");
  GLADE_HOOKUP_OBJECT (window2, label103d, "label103d");
  GLADE_HOOKUP_OBJECT (window2, label104d, "label104d");
  GLADE_HOOKUP_OBJECT (window2, label106, "label106");
  GLADE_HOOKUP_OBJECT (window2, button13d, "button13d");
  GLADE_HOOKUP_OBJECT (window2, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window2, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window2, image11, "image11");
  GLADE_HOOKUP_OBJECT (window2, label83, "label83");
  GLADE_HOOKUP_OBJECT (window2, button14d, "button14d");
  GLADE_HOOKUP_OBJECT (window2, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window2, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window2, image12, "image12");
  GLADE_HOOKUP_OBJECT (window2, label84, "label84");

  return window2;
}

