/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window3 (void);
GtkWidget* create_window5 (void);
GtkWidget* create_window8 (void);
GtkWidget* create_window10 (void);
GtkWidget* create_window20 (void);
GtkWidget* create_window22 (void);
GtkWidget* create_window23 (void);
GtkWidget* create_window500 (void);
GtkWidget* create_windowmessage (void);
GtkWidget* create_windowverificationsupp (void);
