/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed3;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *button11;
  GtkWidget *button10;
  GtkWidget *image7;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("athantification window3"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window3), fixed3);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry2, 136, 80);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3, 136, 136);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label1 = gtk_label_new (_("Authentifiez vous"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed3), label1, 152, 32);
  gtk_widget_set_size_request (label1, 144, 24);

  label2 = gtk_label_new (_("Login:"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed3), label2, 40, 80);
  gtk_widget_set_size_request (label2, 65, 25);

  label3 = gtk_label_new (_("Password:"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed3), label3, 40, 136);
  gtk_widget_set_size_request (label3, 88, 24);

  label4 = gtk_label_new ("");
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed3), label4, 112, 176);
  gtk_widget_set_size_request (label4, 216, 33);

  button11 = gtk_button_new_with_mnemonic (_("Se connecter"));
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed3), button11, 328, 224);
  gtk_widget_set_size_request (button11, 98, 29);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed3), button10, 24, 216);
  gtk_widget_set_size_request (button10, 74, 29);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_container_add (GTK_CONTAINER (button10), image7);

  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window3, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window3, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window3, label1, "label1");
  GLADE_HOOKUP_OBJECT (window3, label2, "label2");
  GLADE_HOOKUP_OBJECT (window3, label3, "label3");
  GLADE_HOOKUP_OBJECT (window3, label4, "label4");
  GLADE_HOOKUP_OBJECT (window3, button11, "button11");
  GLADE_HOOKUP_OBJECT (window3, button10, "button10");
  GLADE_HOOKUP_OBJECT (window3, image7, "image7");

  return window3;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *fixed5;
  GtkWidget *hseparator1;
  GtkWidget *vseparator1;
  GtkWidget *button16;
  GtkWidget *button17;
  GtkWidget *button18;
  GtkWidget *button19;
  GtkWidget *button15;
  GtkWidget *image10;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("client window5"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window5), fixed5);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed5), hseparator1, 0, 40);
  gtk_widget_set_size_request (hseparator1, 408, 32);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed5), vseparator1, 72, 56);
  gtk_widget_set_size_request (vseparator1, 32, 248);

  button16 = gtk_button_new_with_mnemonic (_("Prestations"));
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed5), button16, 184, 96);
  gtk_widget_set_size_request (button16, 104, 32);

  button17 = gtk_button_new_with_mnemonic (_("Factures"));
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed5), button17, 184, 160);
  gtk_widget_set_size_request (button17, 104, 32);

  button18 = gtk_button_new_with_mnemonic (_("G\303\251rer  \ncompte"));
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed5), button18, 8, 224);
  gtk_widget_set_size_request (button18, 74, 53);

  button19 = gtk_button_new_with_mnemonic (_("Reclamations"));
  gtk_widget_show (button19);
  gtk_fixed_put (GTK_FIXED (fixed5), button19, 184, 224);
  gtk_widget_set_size_request (button19, 104, 29);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed5), button15, 392, 8);
  gtk_widget_set_size_request (button15, 40, 32);

  image10 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_container_add (GTK_CONTAINER (button15), image10);

  g_signal_connect ((gpointer) button18, "clicked",
                    G_CALLBACK (on_button18_clicked),
                    NULL);
  g_signal_connect ((gpointer) button19, "clicked",
                    G_CALLBACK (on_button19_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window5, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (window5, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (window5, button16, "button16");
  GLADE_HOOKUP_OBJECT (window5, button17, "button17");
  GLADE_HOOKUP_OBJECT (window5, button18, "button18");
  GLADE_HOOKUP_OBJECT (window5, button19, "button19");
  GLADE_HOOKUP_OBJECT (window5, button15, "button15");
  GLADE_HOOKUP_OBJECT (window5, image10, "image10");

  return window5;
}

GtkWidget*
create_window8 (void)
{
  GtkWidget *window8;
  GtkWidget *fixed8;
  GtkWidget *entry10;
  GtkWidget *type_reclamation;
  GtkWidget *label127;
  GtkWidget *button26;
  GtkWidget *image15;
  GtkWidget *button28;
  GtkWidget *image16;
  GtkWidget *comboboxentry1;
  GtkWidget *button27;
  GtkWidget *button88;

  window8 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window8), _("redaction_recwindow8"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (window8), fixed8);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed8), entry10, 80, 80);
  gtk_widget_set_size_request (entry10, 216, 144);
  GTK_WIDGET_SET_FLAGS (entry10, GTK_CAN_DEFAULT);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);
  gtk_entry_set_width_chars (GTK_ENTRY (entry10), 500);

  type_reclamation = gtk_label_new (_("type"));
  gtk_widget_show (type_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed8), type_reclamation, 24, 32);
  gtk_widget_set_size_request (type_reclamation, 57, 17);

  label127 = gtk_label_new (_("context"));
  gtk_widget_show (label127);
  gtk_fixed_put (GTK_FIXED (fixed8), label127, 8, 81);
  gtk_widget_set_size_request (label127, 72, 16);

  button26 = gtk_button_new ();
  gtk_widget_show (button26);
  gtk_fixed_put (GTK_FIXED (fixed8), button26, 304, 16);
  gtk_widget_set_size_request (button26, 56, 32);

  image15 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_container_add (GTK_CONTAINER (button26), image15);

  button28 = gtk_button_new ();
  gtk_widget_show (button28);
  gtk_fixed_put (GTK_FIXED (fixed8), button28, 16, 248);
  gtk_widget_set_size_request (button28, 74, 29);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_container_add (GTK_CONTAINER (button28), image16);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed8), comboboxentry1, 96, 24);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("qualit\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("technique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("vol"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("hotel"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("voiture"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Autre"));

  button27 = gtk_button_new_with_mnemonic (_("Envoyer"));
  gtk_widget_show (button27);
  gtk_fixed_put (GTK_FIXED (fixed8), button27, 280, 248);
  gtk_widget_set_size_request (button27, 74, 29);

  button88 = gtk_button_new_with_mnemonic (_("reponse"));
  gtk_widget_show (button88);
  gtk_fixed_put (GTK_FIXED (fixed8), button88, 192, 248);
  gtk_widget_set_size_request (button88, 74, 29);

  g_signal_connect ((gpointer) button26, "clicked",
                    G_CALLBACK (on_button26_clicked),
                    NULL);
  g_signal_connect ((gpointer) button28, "clicked",
                    G_CALLBACK (on_button28_clicked),
                    NULL);
  g_signal_connect ((gpointer) button27, "clicked",
                    G_CALLBACK (on_button27_clicked),
                    NULL);
  g_signal_connect ((gpointer) button88, "clicked",
                    G_CALLBACK (on_button88_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window8, window8, "window8");
  GLADE_HOOKUP_OBJECT (window8, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window8, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (window8, type_reclamation, "type_reclamation");
  GLADE_HOOKUP_OBJECT (window8, label127, "label127");
  GLADE_HOOKUP_OBJECT (window8, button26, "button26");
  GLADE_HOOKUP_OBJECT (window8, image15, "image15");
  GLADE_HOOKUP_OBJECT (window8, button28, "button28");
  GLADE_HOOKUP_OBJECT (window8, image16, "image16");
  GLADE_HOOKUP_OBJECT (window8, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (window8, button27, "button27");
  GLADE_HOOKUP_OBJECT (window8, button88, "button88");

  gtk_widget_grab_focus (entry10);
  gtk_widget_grab_default (entry10);
  return window8;
}

GtkWidget*
create_window10 (void)
{
  GtkWidget *window10;
  GtkWidget *fixed10;
  GtkWidget *label18;
  GtkWidget *image20;
  GtkWidget *image21;
  GtkWidget *button33;
  GtkWidget *button35;
  GtkWidget *button36;
  GtkWidget *button34;
  GtkWidget *button32;
  GtkWidget *image19;

  window10 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window10), _("interface_adminwindow10"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (window10), fixed10);

  label18 = gtk_label_new (_("Interface admin"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed10), label18, 144, 8);
  gtk_widget_set_size_request (label18, 176, 40);

  image20 = create_pixmap (window10, "index.png");
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed10), image20, 256, 40);
  gtk_widget_set_size_request (image20, 232, 120);

  image21 = create_pixmap (window10, "index.jpeg");
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (fixed10), image21, 16, 40);
  gtk_widget_set_size_request (image21, 240, 120);

  button33 = gtk_button_new_with_mnemonic (_("gerer compte agent"));
  gtk_widget_show (button33);
  gtk_fixed_put (GTK_FIXED (fixed10), button33, 176, 208);
  gtk_widget_set_size_request (button33, 160, 29);

  button35 = gtk_button_new_with_mnemonic (_("Gerer compte clients"));
  gtk_widget_show (button35);
  gtk_fixed_put (GTK_FIXED (fixed10), button35, 176, 256);
  gtk_widget_set_size_request (button35, 160, 29);

  button36 = gtk_button_new_with_mnemonic (_("gerer mon \ncompte"));
  gtk_widget_show (button36);
  gtk_fixed_put (GTK_FIXED (fixed10), button36, 24, 272);
  gtk_widget_set_size_request (button36, 90, 74);

  button34 = gtk_button_new_with_mnemonic (_("gerer reclamations"));
  gtk_widget_show (button34);
  gtk_fixed_put (GTK_FIXED (fixed10), button34, 176, 304);
  gtk_widget_set_size_request (button34, 160, 29);

  button32 = gtk_button_new ();
  gtk_widget_show (button32);
  gtk_fixed_put (GTK_FIXED (fixed10), button32, 480, 0);
  gtk_widget_set_size_request (button32, 40, 40);

  image19 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_container_add (GTK_CONTAINER (button32), image19);

  g_signal_connect ((gpointer) button33, "clicked",
                    G_CALLBACK (on_button33_clicked),
                    NULL);
  g_signal_connect ((gpointer) button35, "clicked",
                    G_CALLBACK (on_button35_clicked),
                    NULL);
  g_signal_connect ((gpointer) button36, "clicked",
                    G_CALLBACK (on_button36_clicked),
                    NULL);
  g_signal_connect ((gpointer) button34, "clicked",
                    G_CALLBACK (on_button34_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window10, window10, "window10");
  GLADE_HOOKUP_OBJECT (window10, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window10, label18, "label18");
  GLADE_HOOKUP_OBJECT (window10, image20, "image20");
  GLADE_HOOKUP_OBJECT (window10, image21, "image21");
  GLADE_HOOKUP_OBJECT (window10, button33, "button33");
  GLADE_HOOKUP_OBJECT (window10, button35, "button35");
  GLADE_HOOKUP_OBJECT (window10, button36, "button36");
  GLADE_HOOKUP_OBJECT (window10, button34, "button34");
  GLADE_HOOKUP_OBJECT (window10, button32, "button32");
  GLADE_HOOKUP_OBJECT (window10, image19, "image19");

  return window10;
}

GtkWidget*
create_window20 (void)
{
  GtkWidget *window20;
  GtkWidget *fixed20;
  GtkWidget *treeview5;
  GtkWidget *label52;
  GtkWidget *button67;
  GtkWidget *image42;
  GtkWidget *button68;
  GtkWidget *button69;
  GtkWidget *image43;

  window20 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window20), _("treviewrecwindow20"));

  fixed20 = gtk_fixed_new ();
  gtk_widget_show (fixed20);
  gtk_container_add (GTK_CONTAINER (window20), fixed20);

  treeview5 = gtk_tree_view_new ();
  gtk_widget_show (treeview5);
  gtk_fixed_put (GTK_FIXED (fixed20), treeview5, 128, 48);
  gtk_widget_set_size_request (treeview5, 300, 200);

  label52 = gtk_label_new (_("Gerer les reclamations"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed20), label52, 168, 16);
  gtk_widget_set_size_request (label52, 192, 25);

  button67 = gtk_button_new ();
  gtk_widget_show (button67);
  gtk_fixed_put (GTK_FIXED (fixed20), button67, 528, 0);
  gtk_widget_set_size_request (button67, 42, 39);

  image42 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image42);
  gtk_container_add (GTK_CONTAINER (button67), image42);

  button68 = gtk_button_new_with_mnemonic (_("Consulter"));
  gtk_widget_show (button68);
  gtk_fixed_put (GTK_FIXED (fixed20), button68, 376, 256);
  gtk_widget_set_size_request (button68, 160, 29);

  button69 = gtk_button_new ();
  gtk_widget_show (button69);
  gtk_fixed_put (GTK_FIXED (fixed20), button69, 16, 264);
  gtk_widget_set_size_request (button69, 66, 29);

  image43 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image43);
  gtk_container_add (GTK_CONTAINER (button69), image43);

  g_signal_connect ((gpointer) button67, "clicked",
                    G_CALLBACK (on_button67_clicked),
                    NULL);
  g_signal_connect ((gpointer) button68, "clicked",
                    G_CALLBACK (on_button68_clicked),
                    NULL);
  g_signal_connect ((gpointer) button69, "clicked",
                    G_CALLBACK (on_button69_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window20, window20, "window20");
  GLADE_HOOKUP_OBJECT (window20, fixed20, "fixed20");
  GLADE_HOOKUP_OBJECT (window20, treeview5, "treeview5");
  GLADE_HOOKUP_OBJECT (window20, label52, "label52");
  GLADE_HOOKUP_OBJECT (window20, button67, "button67");
  GLADE_HOOKUP_OBJECT (window20, image42, "image42");
  GLADE_HOOKUP_OBJECT (window20, button68, "button68");
  GLADE_HOOKUP_OBJECT (window20, button69, "button69");
  GLADE_HOOKUP_OBJECT (window20, image43, "image43");

  return window20;
}

GtkWidget*
create_window22 (void)
{
  GtkWidget *window22;
  GtkWidget *fixed22;
  GtkWidget *button74;
  GtkWidget *label132;
  GtkWidget *label56;
  GtkWidget *label54;
  GtkWidget *label555;
  GtkWidget *label577;
  GtkWidget *label1312;
  GtkWidget *entry26;
  GtkWidget *button71;
  GtkWidget *button76;
  GtkWidget *button73;
  GtkWidget *image46;
  GtkWidget *button75;
  GtkWidget *image47;
  GtkWidget *label1311;

  window22 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window22), _("voirrecwindow22"));

  fixed22 = gtk_fixed_new ();
  gtk_widget_show (fixed22);
  gtk_container_add (GTK_CONTAINER (window22), fixed22);
  gtk_widget_set_size_request (fixed22, 528, 301);

  button74 = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (button74);
  gtk_fixed_put (GTK_FIXED (fixed22), button74, 312, 512);
  gtk_widget_set_size_request (button74, 160, 29);

  label132 = gtk_label_new (_("context"));
  gtk_widget_show (label132);
  gtk_fixed_put (GTK_FIXED (fixed22), label132, 24, 240);
  gtk_widget_set_size_request (label132, 57, 17);

  label56 = gtk_label_new (_("Type:"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed22), label56, 24, 192);
  gtk_widget_set_size_request (label56, 57, 17);

  label54 = gtk_label_new (_("Nom du client:"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed22), label54, 0, 160);
  gtk_widget_set_size_request (label54, 105, 25);

  label555 = gtk_label_new (_("vide"));
  gtk_widget_show (label555);
  gtk_fixed_put (GTK_FIXED (fixed22), label555, 128, 160);
  gtk_widget_set_size_request (label555, 112, 25);

  label577 = gtk_label_new_with_mnemonic (_("vide"));
  gtk_widget_show (label577);
  gtk_fixed_put (GTK_FIXED (fixed22), label577, 128, 192);
  gtk_widget_set_size_request (label577, 96, 25);

  label1312 = gtk_label_new (_("Numero de \nla reclamation"));
  gtk_widget_show (label1312);
  gtk_fixed_put (GTK_FIXED (fixed22), label1312, 8, 24);
  gtk_widget_set_size_request (label1312, 104, 48);

  entry26 = gtk_entry_new ();
  gtk_widget_show (entry26);
  gtk_fixed_put (GTK_FIXED (fixed22), entry26, 152, 40);
  gtk_widget_set_size_request (entry26, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry26), 8226);

  button71 = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (button71);
  gtk_fixed_put (GTK_FIXED (fixed22), button71, 352, 40);
  gtk_widget_set_size_request (button71, 104, 37);

  button76 = gtk_button_new_with_mnemonic (_("repondre"));
  gtk_widget_show (button76);
  gtk_fixed_put (GTK_FIXED (fixed22), button76, 168, 512);
  gtk_widget_set_size_request (button76, 114, 29);

  button73 = gtk_button_new ();
  gtk_widget_show (button73);
  gtk_fixed_put (GTK_FIXED (fixed22), button73, 656, 8);
  gtk_widget_set_size_request (button73, 40, 39);

  image46 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image46);
  gtk_container_add (GTK_CONTAINER (button73), image46);

  button75 = gtk_button_new ();
  gtk_widget_show (button75);
  gtk_fixed_put (GTK_FIXED (fixed22), button75, 8, 528);
  gtk_widget_set_size_request (button75, 66, 29);

  image47 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image47);
  gtk_container_add (GTK_CONTAINER (button75), image47);

  label1311 = gtk_label_new (_("vide"));
  gtk_widget_show (label1311);
  gtk_fixed_put (GTK_FIXED (fixed22), label1311, 120, 232);
  gtk_widget_set_size_request (label1311, 440, 248);
  GTK_WIDGET_SET_FLAGS (label1311, GTK_CAN_FOCUS);
  gtk_label_set_line_wrap (GTK_LABEL (label1311), TRUE);
  gtk_label_set_selectable (GTK_LABEL (label1311), TRUE);
  gtk_label_set_ellipsize (GTK_LABEL (label1311), PANGO_ELLIPSIZE_START);

  g_signal_connect ((gpointer) button74, "clicked",
                    G_CALLBACK (on_button74_clicked),
                    NULL);
  g_signal_connect ((gpointer) button71, "clicked",
                    G_CALLBACK (on_button71_clicked),
                    NULL);
  g_signal_connect ((gpointer) button76, "clicked",
                    G_CALLBACK (on_button76_clicked),
                    NULL);
  g_signal_connect ((gpointer) button73, "clicked",
                    G_CALLBACK (on_button73_clicked),
                    NULL);
  g_signal_connect ((gpointer) button75, "clicked",
                    G_CALLBACK (on_button75_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window22, window22, "window22");
  GLADE_HOOKUP_OBJECT (window22, fixed22, "fixed22");
  GLADE_HOOKUP_OBJECT (window22, button74, "button74");
  GLADE_HOOKUP_OBJECT (window22, label132, "label132");
  GLADE_HOOKUP_OBJECT (window22, label56, "label56");
  GLADE_HOOKUP_OBJECT (window22, label54, "label54");
  GLADE_HOOKUP_OBJECT (window22, label555, "label555");
  GLADE_HOOKUP_OBJECT (window22, label577, "label577");
  GLADE_HOOKUP_OBJECT (window22, label1312, "label1312");
  GLADE_HOOKUP_OBJECT (window22, entry26, "entry26");
  GLADE_HOOKUP_OBJECT (window22, button71, "button71");
  GLADE_HOOKUP_OBJECT (window22, button76, "button76");
  GLADE_HOOKUP_OBJECT (window22, button73, "button73");
  GLADE_HOOKUP_OBJECT (window22, image46, "image46");
  GLADE_HOOKUP_OBJECT (window22, button75, "button75");
  GLADE_HOOKUP_OBJECT (window22, image47, "image47");
  GLADE_HOOKUP_OBJECT (window22, label1311, "label1311");

  return window22;
}

GtkWidget*
create_window23 (void)
{
  GtkWidget *window23;
  GtkWidget *fixed23;
  GtkWidget *entry27;
  GtkWidget *label58;
  GtkWidget *button78;
  GtkWidget *image49;
  GtkWidget *button77;
  GtkWidget *image48;
  GtkWidget *button79;

  window23 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window23), _("repondrewindow23"));

  fixed23 = gtk_fixed_new ();
  gtk_widget_show (fixed23);
  gtk_container_add (GTK_CONTAINER (window23), fixed23);

  entry27 = gtk_entry_new ();
  gtk_widget_show (entry27);
  gtk_fixed_put (GTK_FIXED (fixed23), entry27, 104, 80);
  gtk_widget_set_size_request (entry27, 192, 160);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry27), 8226);

  label58 = gtk_label_new (_("Rediger une modification:"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed23), label58, 72, 40);
  gtk_widget_set_size_request (label58, 184, 25);

  button78 = gtk_button_new ();
  gtk_widget_show (button78);
  gtk_fixed_put (GTK_FIXED (fixed23), button78, 344, 16);
  gtk_widget_set_size_request (button78, 56, 29);

  image49 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image49);
  gtk_container_add (GTK_CONTAINER (button78), image49);

  button77 = gtk_button_new ();
  gtk_widget_show (button77);
  gtk_fixed_put (GTK_FIXED (fixed23), button77, 8, 280);
  gtk_widget_set_size_request (button77, 74, 29);

  image48 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image48);
  gtk_container_add (GTK_CONTAINER (button77), image48);

  button79 = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (button79);
  gtk_fixed_put (GTK_FIXED (fixed23), button79, 320, 272);
  gtk_widget_set_size_request (button79, 74, 29);

  g_signal_connect ((gpointer) button78, "clicked",
                    G_CALLBACK (on_button78_clicked),
                    NULL);
  g_signal_connect ((gpointer) button77, "clicked",
                    G_CALLBACK (on_button77_clicked),
                    NULL);
  g_signal_connect ((gpointer) button79, "clicked",
                    G_CALLBACK (on_button79_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window23, window23, "window23");
  GLADE_HOOKUP_OBJECT (window23, fixed23, "fixed23");
  GLADE_HOOKUP_OBJECT (window23, entry27, "entry27");
  GLADE_HOOKUP_OBJECT (window23, label58, "label58");
  GLADE_HOOKUP_OBJECT (window23, button78, "button78");
  GLADE_HOOKUP_OBJECT (window23, image49, "image49");
  GLADE_HOOKUP_OBJECT (window23, button77, "button77");
  GLADE_HOOKUP_OBJECT (window23, image48, "image48");
  GLADE_HOOKUP_OBJECT (window23, button79, "button79");

  return window23;
}

GtkWidget*
create_window500 (void)
{
  GtkWidget *window500;
  GtkWidget *fixed24;
  GtkWidget *button83;
  GtkWidget *image51;
  GtkWidget *button85;
  GtkWidget *image53;
  GtkWidget *label1313;
  GtkWidget *button84;
  GtkWidget *image52;
  GtkWidget *label128;

  window500 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window500), _("windowreponse"));

  fixed24 = gtk_fixed_new ();
  gtk_widget_show (fixed24);
  gtk_container_add (GTK_CONTAINER (window500), fixed24);

  button83 = gtk_button_new ();
  gtk_widget_show (button83);
  gtk_fixed_put (GTK_FIXED (fixed24), button83, 656, 8);
  gtk_widget_set_size_request (button83, 40, 39);

  image51 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image51);
  gtk_container_add (GTK_CONTAINER (button83), image51);

  button85 = gtk_button_new ();
  gtk_widget_show (button85);
  gtk_fixed_put (GTK_FIXED (fixed24), button85, 8, 528);
  gtk_widget_set_size_request (button85, 66, 29);

  image53 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image53);
  gtk_container_add (GTK_CONTAINER (button85), image53);

  label1313 = gtk_label_new (_("reponse "));
  gtk_widget_show (label1313);
  gtk_fixed_put (GTK_FIXED (fixed24), label1313, 32, 104);
  gtk_widget_set_size_request (label1313, 65, 17);

  button84 = gtk_button_new ();
  gtk_widget_show (button84);
  gtk_fixed_put (GTK_FIXED (fixed24), button84, 656, 8);
  gtk_widget_set_size_request (button84, 40, 39);

  image52 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image52);
  gtk_container_add (GTK_CONTAINER (button84), image52);

  label128 = gtk_label_new (_("aucune reponse"));
  gtk_widget_show (label128);
  gtk_fixed_put (GTK_FIXED (fixed24), label128, 128, 136);
  gtk_widget_set_size_request (label128, 400, 288);
  gtk_label_set_line_wrap (GTK_LABEL (label128), TRUE);
  gtk_label_set_ellipsize (GTK_LABEL (label128), PANGO_ELLIPSIZE_START);

  g_signal_connect ((gpointer) button83, "clicked",
                    G_CALLBACK (on_button73_clicked),
                    NULL);
  g_signal_connect ((gpointer) button85, "clicked",
                    G_CALLBACK (on_button85_clicked),
                    NULL);
  g_signal_connect ((gpointer) button84, "clicked",
                    G_CALLBACK (on_button84_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window500, window500, "window500");
  GLADE_HOOKUP_OBJECT (window500, fixed24, "fixed24");
  GLADE_HOOKUP_OBJECT (window500, button83, "button83");
  GLADE_HOOKUP_OBJECT (window500, image51, "image51");
  GLADE_HOOKUP_OBJECT (window500, button85, "button85");
  GLADE_HOOKUP_OBJECT (window500, image53, "image53");
  GLADE_HOOKUP_OBJECT (window500, label1313, "label1313");
  GLADE_HOOKUP_OBJECT (window500, button84, "button84");
  GLADE_HOOKUP_OBJECT (window500, image52, "image52");
  GLADE_HOOKUP_OBJECT (window500, label128, "label128");

  return window500;
}

GtkWidget*
create_windowmessage (void)
{
  GtkWidget *windowmessage;
  GtkWidget *fixed25;
  GtkWidget *label129;

  windowmessage = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowmessage), _("windowmessage"));

  fixed25 = gtk_fixed_new ();
  gtk_widget_show (fixed25);
  gtk_container_add (GTK_CONTAINER (windowmessage), fixed25);

  label129 = gtk_label_new (_("opertion effectuee"));
  gtk_widget_show (label129);
  gtk_fixed_put (GTK_FIXED (fixed25), label129, 96, 88);
  gtk_widget_set_size_request (label129, 232, 65);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowmessage, windowmessage, "windowmessage");
  GLADE_HOOKUP_OBJECT (windowmessage, fixed25, "fixed25");
  GLADE_HOOKUP_OBJECT (windowmessage, label129, "label129");

  return windowmessage;
}

GtkWidget*
create_windowverificationsupp (void)
{
  GtkWidget *windowverificationsupp;
  GtkWidget *fixed26;
  GtkWidget *label130;
  GtkWidget *button81;

  windowverificationsupp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowverificationsupp), _("windowverificationsupp"));

  fixed26 = gtk_fixed_new ();
  gtk_widget_show (fixed26);
  gtk_container_add (GTK_CONTAINER (windowverificationsupp), fixed26);

  label130 = gtk_label_new (_("confirmation de l'opration"));
  gtk_widget_show (label130);
  gtk_fixed_put (GTK_FIXED (fixed26), label130, 112, 80);
  gtk_widget_set_size_request (label130, 200, 16);

  button81 = gtk_button_new_with_mnemonic (_("confirmer la supprission"));
  gtk_widget_show (button81);
  gtk_fixed_put (GTK_FIXED (fixed26), button81, 120, 128);
  gtk_widget_set_size_request (button81, 192, 48);

  g_signal_connect ((gpointer) button81, "clicked",
                    G_CALLBACK (on_button81_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowverificationsupp, windowverificationsupp, "windowverificationsupp");
  GLADE_HOOKUP_OBJECT (windowverificationsupp, fixed26, "fixed26");
  GLADE_HOOKUP_OBJECT (windowverificationsupp, label130, "label130");
  GLADE_HOOKUP_OBJECT (windowverificationsupp, button81, "button81");

  return windowverificationsupp;
}

