/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *window1;
  GtkWidget *window2;
  GtkWidget *window3;
  GtkWidget *window4;
  GtkWidget *window5;
  GtkWidget *window6;
  GtkWidget *window7;
  GtkWidget *window8;
  GtkWidget *window9;
  GtkWidget *window10;
  GtkWidget *window11;
  GtkWidget *window12;
  GtkWidget *window13;
  GtkWidget *window14;
  GtkWidget *window15;
  GtkWidget *window16;
  GtkWidget *window17;
  GtkWidget *window18;
  GtkWidget *window19;
  GtkWidget *window20;
  GtkWidget *window21;
  GtkWidget *window22;
  GtkWidget *window23;
  GtkWidget *window24;
  GtkWidget *window25;
  GtkWidget *window26;
  GtkWidget *window27;
  GtkWidget *window28;
  GtkWidget *window29;
  GtkWidget *window30;
  GtkWidget *window31;
  GtkWidget *window32;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  
  
  window3 = create_window3 ();
  gtk_widget_show (window3);
  
  
 
  gtk_main ();
  return 0;
}

