/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_acceuil (void);
GtkWidget* create_gestion_vol (void);
GtkWidget* create_window (void);
GtkWidget* create_window1 (void);
