/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_acceuil (void)
{
  GtkWidget *acceuil;
  GtkWidget *fixed1;
  GtkWidget *image14;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;

  acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (acceuil, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (acceuil), _("acceuil"));
  gtk_window_set_position (GTK_WINDOW (acceuil), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (acceuil), FALSE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (acceuil), fixed1);

  image14 = create_pixmap (acceuil, "people-inside-commercial-air-plane-1309644 (1).jpg");
  gtk_widget_show (image14);
  gtk_fixed_put (GTK_FIXED (fixed1), image14, 0, 0);
  gtk_widget_set_size_request (image14, 1000, 704);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 416, 120);
  gtk_widget_set_size_request (button1, 168, 72);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Gestion des vols"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_Acceuilgestion_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (acceuil, acceuil, "acceuil");
  GLADE_HOOKUP_OBJECT (acceuil, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (acceuil, image14, "image14");
  GLADE_HOOKUP_OBJECT (acceuil, button1, "button1");
  GLADE_HOOKUP_OBJECT (acceuil, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (acceuil, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (acceuil, image1, "image1");
  GLADE_HOOKUP_OBJECT (acceuil, label1, "label1");

  return acceuil;
}

GtkWidget*
create_gestion_vol (void)
{
  GtkWidget *gestion_vol;
  GtkWidget *fixed2;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkWidget *entry1;
  GtkWidget *calendar1;
  GtkWidget *calendar2;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *image10;
  GtkWidget *label14;
  GtkWidget *label11;
  GtkWidget *label4;
  GtkWidget *label12;
  GtkWidget *label5;
  GtkWidget *label13;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *button4;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label10;
  GtkWidget *label7;
  GtkWidget *label6;
  GtkWidget *combobox1;
  GtkWidget *combobox4;
  GtkWidget *combobox6;
  GtkWidget *label15;
  GtkWidget *fixed4;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkWidget *image11;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label16;
  GtkWidget *label44;
  GtkWidget *label47;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *button6;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label22;
  GtkWidget *button5;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label21;
  GtkWidget *button8;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label49;
  GtkWidget *combobox2;
  GtkWidget *combobox5;
  GtkWidget *combobox7;
  GtkWidget *label27;
  GtkWidget *fixed5;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkWidget *image12;
  GtkWidget *label57;
  GtkWidget *label50;
  GtkWidget *label51;
  GtkWidget *label28;
  GtkWidget *label30;
  GtkWidget *label32;
  GtkWidget *label34;
  GtkWidget *label36;
  GtkWidget *label39;
  GtkWidget *label53;
  GtkWidget *label55;
  GtkWidget *label56;
  GtkWidget *button7;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label48;
  GtkWidget *label29;
  GtkWidget *label31;
  GtkWidget *label33;
  GtkWidget *label35;
  GtkWidget *label37;
  GtkWidget *label52;
  GtkWidget *label54;
  GtkWidget *label41;
  GtkWidget *fixed6;
  GtkWidget *entry4;
  GtkWidget *image13;
  GtkWidget *label61;
  GtkWidget *label62;
  GtkWidget *button9;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label63;
  GtkWidget *label59;
  GtkWidget *label60;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview2;
  GtkWidget *label58;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;

  gestion_vol = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gestion_vol, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (gestion_vol), _("Gestion Vols"));
  gtk_window_set_position (GTK_WINDOW (gestion_vol), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (gestion_vol), FALSE);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (gestion_vol), fixed2);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 1600, 640);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1, 152, 96);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed3), calendar1, 752, 32);
  gtk_widget_set_size_request (calendar1, 236, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  calendar2 = gtk_calendar_new ();
  gtk_widget_show (calendar2);
  gtk_fixed_put (GTK_FIXED (fixed3), calendar2, 752, 256);
  gtk_widget_set_size_request (calendar2, 236, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar2),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 50, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton1, 504, 376);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (1, 200, 1200, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton2, 184, 368);
  gtk_widget_set_size_request (spinbutton2, 56, 27);

  image10 = create_pixmap (gestion_vol, "above-atmosphere-clouds-flight-37728 (2).jpg");
  gtk_widget_show (image10);
  gtk_fixed_put (GTK_FIXED (fixed3), image10, 0, 0);
  gtk_widget_set_size_request (image10, 1040, 608);

  label14 = gtk_label_new (_("<span foreground=\"blue\"><i>Vol ajout\303\251 avec succ\303\251s</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 0, 8);
  gtk_widget_set_size_request (label14, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  label11 = gtk_label_new (_("<span foreground=\"red\"><b>Vol existe d\303\251ja !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 320, 16);
  gtk_widget_set_size_request (label11, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  label4 = gtk_label_new (_("Id : "));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed3), label4, 72, 88);
  gtk_widget_set_size_request (label4, 80, 48);

  label12 = gtk_label_new (_("<span foreground=\"red\"><b>Saisir id !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 272, 72);
  gtk_widget_set_size_request (label12, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);

  label5 = gtk_label_new (_("Depart : "));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed3), label5, 32, 152);
  gtk_widget_set_size_request (label5, 128, 48);

  label13 = gtk_label_new (_("<span foreground=\"red\"><b>Choisir Depart !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 280, 144);
  gtk_widget_set_size_request (label13, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  label42 = gtk_label_new (_("Destination : "));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed3), label42, 24, 224);
  gtk_widget_set_size_request (label42, 128, 48);

  label43 = gtk_label_new (_("<span foreground=\"red\"><b>Choisir Destination  !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label43, 288, 216);
  gtk_widget_set_size_request (label43, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  label45 = gtk_label_new (_("Companie : "));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed3), label45, 16, 296);
  gtk_widget_set_size_request (label45, 128, 48);

  label46 = gtk_label_new (_("<span foreground=\"red\"><b>Choisir Companie !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label46, 280, 280);
  gtk_widget_set_size_request (label46, 256, 80);
  gtk_label_set_use_markup (GTK_LABEL (label46), TRUE);

  label8 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed3), label8, 16, 352);
  gtk_widget_set_size_request (label8, 128, 56);

  label9 = gtk_label_new (_("Vols disponible : "));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 336, 360);
  gtk_widget_set_size_request (label9, 136, 56);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed3), button4, 456, 504);
  gtk_widget_set_size_request (button4, 96, 53);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox4), label10, FALSE, FALSE, 0);

  label7 = gtk_label_new (_("Date de retour : "));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed3), label7, 584, 296);
  gtk_widget_set_size_request (label7, 128, 48);

  label6 = gtk_label_new (_("Date de depart : "));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed3), label6, 584, 88);
  gtk_widget_set_size_request (label6, 128, 48);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox1, 152, 160);
  gtk_widget_set_size_request (combobox1, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Tunisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Djerba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Monastir"));

  combobox4 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox4, 152, 232);
  gtk_widget_set_size_request (combobox4, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Marroc"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Paris"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Newyork"));

  combobox6 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox6);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox6, 152, 304);
  gtk_widget_set_size_request (combobox6, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Airfrance"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("tunisair"));

  label15 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label15);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label15);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed4), entry2, 800, 336);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed4), entry3, 800, 400);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  spinbutton3_adj = gtk_adjustment_new (1, 1, 50, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton3, 840, 448);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  spinbutton4_adj = gtk_adjustment_new (1, 200, 1200, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton4, 840, 496);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  image11 = create_pixmap (gestion_vol, "white-airliner-wing-on-top-of-sea-clouds-2007401 (1).jpg");
  gtk_widget_show (image11);
  gtk_fixed_put (GTK_FIXED (fixed4), image11, 0, 0);
  gtk_widget_set_size_request (image11, 992, 608);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolledwindow1, 0, 72);
  gtk_widget_set_size_request (scrolledwindow1, 584, 384);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_widget_set_size_request (treeview1, 584, 384);

  label25 = gtk_label_new (_("<span foreground=\"red\"><b>Selectionner un Vol !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 0, 0);
  gtk_widget_set_size_request (label25, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  label26 = gtk_label_new (_("<span foreground=\"blue\"><i><b>Vol modifi\303\251 avec succ\303\251s</b></i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label26, 688, 0);
  gtk_widget_set_size_request (label26, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  label23 = gtk_label_new (_("<span foreground=\"white\"><i><b>Modifier le Vol : </b></i></span>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed4), label23, 680, 56);
  gtk_widget_set_size_request (label23, 152, 48);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  label24 = gtk_label_new ("");
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 816, 56);
  gtk_widget_set_size_request (label24, 104, 48);

  label16 = gtk_label_new (_("<span foreground=\"white\"><i><b>Depart : </b></i></span>"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 680, 112);
  gtk_widget_set_size_request (label16, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  label44 = gtk_label_new (_("<span foreground=\"white\"><i><b>Destination :  </b></i></span>"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed4), label44, 680, 176);
  gtk_widget_set_size_request (label44, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);

  label47 = gtk_label_new (_("<span foreground=\"white\"><i><b>Companie :   </b></i></span>"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed4), label47, 680, 248);
  gtk_widget_set_size_request (label47, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);

  label17 = gtk_label_new (_("<span foreground=\"white\"><i><b>Date de depart :    </b></i></span>"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 680, 328);
  gtk_widget_set_size_request (label17, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  label18 = gtk_label_new (_("<span foreground=\"white\"><i><b>Date de retour :    </b></i></span>"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 672, 392);
  gtk_widget_set_size_request (label18, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  label19 = gtk_label_new (_("<span foreground=\"white\"><i><b>Vols disponible :    </b></i></span>"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 664, 440);
  gtk_widget_set_size_request (label19, 144, 48);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  label20 = gtk_label_new (_("<span foreground=\"white\"><i><b>Prix :    </b></i></span>"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 680, 488);
  gtk_widget_set_size_request (label20, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  button6 = gtk_button_new ();
  gtk_fixed_put (GTK_FIXED (fixed4), button6, 744, 544);
  gtk_widget_set_size_request (button6, 96, 53);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox6), label22, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed4), button5, 136, 504);
  gtk_widget_set_size_request (button5, 104, 56);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox5), label21, FALSE, FALSE, 0);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed4), button8, 384, 504);
  gtk_widget_set_size_request (button8, 96, 53);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button8), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox8), label49, FALSE, FALSE, 0);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox2, 792, 120);
  gtk_widget_set_size_request (combobox2, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Tunisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Djerba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Monastir"));

  combobox5 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox5);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox5, 792, 184);
  gtk_widget_set_size_request (combobox5, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("Marroc"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("Paris"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("Newyork"));

  combobox7 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox7, 792, 256);
  gtk_widget_set_size_request (combobox7, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Airfrance"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Tunisair"));

  label27 = gtk_label_new (_("Afficher/Supprimer/Modifier"));
  gtk_widget_show (label27);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label27);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  spinbutton5_adj = gtk_adjustment_new (1, 1, 50, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton5, 744, 264);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  image12 = create_pixmap (gestion_vol, "MoDautumn-background-beautiful-bright-627823 (1).jpg");
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed5), image12, 0, 0);
  gtk_widget_set_size_request (image12, 1000, 608);

  label57 = gtk_label_new (_("<span foreground=\"blue\"><i>Reservation r\303\251ussite</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed5), label57, 0, 0);
  gtk_widget_set_size_request (label57, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label57), TRUE);

  label50 = gtk_label_new (_("Reserver le Vol : "));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed5), label50, 200, 64);
  gtk_widget_set_size_request (label50, 152, 48);

  label51 = gtk_label_new ("");
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed5), label51, 344, 64);
  gtk_widget_set_size_request (label51, 120, 48);

  label28 = gtk_label_new (_("Depart : "));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed5), label28, 208, 128);
  gtk_widget_set_size_request (label28, 128, 48);

  label30 = gtk_label_new (_("Destination : "));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed5), label30, 200, 184);
  gtk_widget_set_size_request (label30, 128, 48);

  label32 = gtk_label_new (_("Companie : "));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed5), label32, 192, 248);
  gtk_widget_set_size_request (label32, 128, 48);

  label34 = gtk_label_new (_("Date de depart : "));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed5), label34, 128, 296);
  gtk_widget_set_size_request (label34, 240, 64);

  label36 = gtk_label_new (_("Date de retour : "));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed5), label36, 176, 360);
  gtk_widget_set_size_request (label36, 128, 48);

  label39 = gtk_label_new (_("Vols disponible : "));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed5), label39, 160, 416);
  gtk_widget_set_size_request (label39, 144, 48);

  label53 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed5), label53, 152, 480);
  gtk_widget_set_size_request (label53, 144, 48);

  label55 = gtk_label_new (_("Nombre des vols : "));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed5), label55, 592, 256);
  gtk_widget_set_size_request (label55, 144, 48);

  label56 = gtk_label_new (_("<span foreground=\"red\"><b> Nombre invalide !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed5), label56, 752, 240);
  gtk_widget_set_size_request (label56, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label56), TRUE);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed5), button7, 704, 352);
  gtk_widget_set_size_request (button7, 96, 53);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button7), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox7), label48, FALSE, FALSE, 0);

  label29 = gtk_label_new ("");
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed5), label29, 360, 128);
  gtk_widget_set_size_request (label29, 128, 48);

  label31 = gtk_label_new ("");
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 368, 184);
  gtk_widget_set_size_request (label31, 128, 48);

  label33 = gtk_label_new ("");
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed5), label33, 368, 248);
  gtk_widget_set_size_request (label33, 128, 48);

  label35 = gtk_label_new ("");
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed5), label35, 312, 296);
  gtk_widget_set_size_request (label35, 240, 64);

  label37 = gtk_label_new ("");
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed5), label37, 360, 360);
  gtk_widget_set_size_request (label37, 128, 48);

  label52 = gtk_label_new ("");
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed5), label52, 352, 416);
  gtk_widget_set_size_request (label52, 144, 48);

  label54 = gtk_label_new ("");
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed5), label54, 352, 480);
  gtk_widget_set_size_request (label54, 144, 48);

  label41 = gtk_label_new (_("Reserver"));
  gtk_widget_show (label41);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label41);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed6), entry4, 768, 216);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  image13 = create_pixmap (gestion_vol, "aerial-view-of-clouds-258149 (1).jpg");
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed6), image13, 0, 0);
  gtk_widget_set_size_request (image13, 1008, 608);

  label61 = gtk_label_new (_("<span foreground=\"green\"><b>Resulta(s) trouv\303\251e(s)</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), label61, 752, 392);
  gtk_widget_set_size_request (label61, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label61), TRUE);

  label62 = gtk_label_new ("");
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed6), label62, 712, 400);
  gtk_widget_set_size_request (label62, 72, 56);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed6), button9, 776, 296);
  gtk_widget_set_size_request (button9, 96, 53);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button9), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label63 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (hbox9), label63, FALSE, FALSE, 0);

  label59 = gtk_label_new (_("<span foreground=\"white\"><b> Companie : </b></span>"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed6), label59, 640, 208);
  gtk_widget_set_size_request (label59, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label59), TRUE);

  label60 = gtk_label_new (_("<span foreground=\"red\"><b>Saisir Companie !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), label60, 696, 88);
  gtk_widget_set_size_request (label60, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label60), TRUE);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed6), scrolledwindow2, 0, 56);
  gtk_widget_set_size_request (scrolledwindow2, 592, 344);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview2);
  gtk_widget_set_size_request (treeview2, 592, 344);

  label58 = gtk_label_new (_("Chercher"));
  gtk_widget_show (label58);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label58);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed2), button2, 872, 640);
  gtk_widget_set_size_request (button2, 96, 53);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 24, 640);
  gtk_widget_set_size_request (button3, 96, 53);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_Ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_Modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_Supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_Reserver_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_Confirmer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_ChercherVol_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_gestionAcceuil_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_vol, gestion_vol, "gestion_vol");
  GLADE_HOOKUP_OBJECT (gestion_vol, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (gestion_vol, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (gestion_vol, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (gestion_vol, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (gestion_vol, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (gestion_vol, calendar2, "calendar2");
  GLADE_HOOKUP_OBJECT (gestion_vol, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (gestion_vol, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (gestion_vol, image10, "image10");
  GLADE_HOOKUP_OBJECT (gestion_vol, label14, "label14");
  GLADE_HOOKUP_OBJECT (gestion_vol, label11, "label11");
  GLADE_HOOKUP_OBJECT (gestion_vol, label4, "label4");
  GLADE_HOOKUP_OBJECT (gestion_vol, label12, "label12");
  GLADE_HOOKUP_OBJECT (gestion_vol, label5, "label5");
  GLADE_HOOKUP_OBJECT (gestion_vol, label13, "label13");
  GLADE_HOOKUP_OBJECT (gestion_vol, label42, "label42");
  GLADE_HOOKUP_OBJECT (gestion_vol, label43, "label43");
  GLADE_HOOKUP_OBJECT (gestion_vol, label45, "label45");
  GLADE_HOOKUP_OBJECT (gestion_vol, label46, "label46");
  GLADE_HOOKUP_OBJECT (gestion_vol, label8, "label8");
  GLADE_HOOKUP_OBJECT (gestion_vol, label9, "label9");
  GLADE_HOOKUP_OBJECT (gestion_vol, button4, "button4");
  GLADE_HOOKUP_OBJECT (gestion_vol, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion_vol, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion_vol, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion_vol, label10, "label10");
  GLADE_HOOKUP_OBJECT (gestion_vol, label7, "label7");
  GLADE_HOOKUP_OBJECT (gestion_vol, label6, "label6");
  GLADE_HOOKUP_OBJECT (gestion_vol, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (gestion_vol, combobox4, "combobox4");
  GLADE_HOOKUP_OBJECT (gestion_vol, combobox6, "combobox6");
  GLADE_HOOKUP_OBJECT (gestion_vol, label15, "label15");
  GLADE_HOOKUP_OBJECT (gestion_vol, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (gestion_vol, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (gestion_vol, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (gestion_vol, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (gestion_vol, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (gestion_vol, image11, "image11");
  GLADE_HOOKUP_OBJECT (gestion_vol, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (gestion_vol, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (gestion_vol, label25, "label25");
  GLADE_HOOKUP_OBJECT (gestion_vol, label26, "label26");
  GLADE_HOOKUP_OBJECT (gestion_vol, label23, "label23");
  GLADE_HOOKUP_OBJECT (gestion_vol, label24, "label24");
  GLADE_HOOKUP_OBJECT (gestion_vol, label16, "label16");
  GLADE_HOOKUP_OBJECT (gestion_vol, label44, "label44");
  GLADE_HOOKUP_OBJECT (gestion_vol, label47, "label47");
  GLADE_HOOKUP_OBJECT (gestion_vol, label17, "label17");
  GLADE_HOOKUP_OBJECT (gestion_vol, label18, "label18");
  GLADE_HOOKUP_OBJECT (gestion_vol, label19, "label19");
  GLADE_HOOKUP_OBJECT (gestion_vol, label20, "label20");
  GLADE_HOOKUP_OBJECT (gestion_vol, button6, "button6");
  GLADE_HOOKUP_OBJECT (gestion_vol, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion_vol, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion_vol, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestion_vol, label22, "label22");
  GLADE_HOOKUP_OBJECT (gestion_vol, button5, "button5");
  GLADE_HOOKUP_OBJECT (gestion_vol, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestion_vol, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestion_vol, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestion_vol, label21, "label21");
  GLADE_HOOKUP_OBJECT (gestion_vol, button8, "button8");
  GLADE_HOOKUP_OBJECT (gestion_vol, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (gestion_vol, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (gestion_vol, image8, "image8");
  GLADE_HOOKUP_OBJECT (gestion_vol, label49, "label49");
  GLADE_HOOKUP_OBJECT (gestion_vol, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (gestion_vol, combobox5, "combobox5");
  GLADE_HOOKUP_OBJECT (gestion_vol, combobox7, "combobox7");
  GLADE_HOOKUP_OBJECT (gestion_vol, label27, "label27");
  GLADE_HOOKUP_OBJECT (gestion_vol, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (gestion_vol, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (gestion_vol, image12, "image12");
  GLADE_HOOKUP_OBJECT (gestion_vol, label57, "label57");
  GLADE_HOOKUP_OBJECT (gestion_vol, label50, "label50");
  GLADE_HOOKUP_OBJECT (gestion_vol, label51, "label51");
  GLADE_HOOKUP_OBJECT (gestion_vol, label28, "label28");
  GLADE_HOOKUP_OBJECT (gestion_vol, label30, "label30");
  GLADE_HOOKUP_OBJECT (gestion_vol, label32, "label32");
  GLADE_HOOKUP_OBJECT (gestion_vol, label34, "label34");
  GLADE_HOOKUP_OBJECT (gestion_vol, label36, "label36");
  GLADE_HOOKUP_OBJECT (gestion_vol, label39, "label39");
  GLADE_HOOKUP_OBJECT (gestion_vol, label53, "label53");
  GLADE_HOOKUP_OBJECT (gestion_vol, label55, "label55");
  GLADE_HOOKUP_OBJECT (gestion_vol, label56, "label56");
  GLADE_HOOKUP_OBJECT (gestion_vol, button7, "button7");
  GLADE_HOOKUP_OBJECT (gestion_vol, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (gestion_vol, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (gestion_vol, image7, "image7");
  GLADE_HOOKUP_OBJECT (gestion_vol, label48, "label48");
  GLADE_HOOKUP_OBJECT (gestion_vol, label29, "label29");
  GLADE_HOOKUP_OBJECT (gestion_vol, label31, "label31");
  GLADE_HOOKUP_OBJECT (gestion_vol, label33, "label33");
  GLADE_HOOKUP_OBJECT (gestion_vol, label35, "label35");
  GLADE_HOOKUP_OBJECT (gestion_vol, label37, "label37");
  GLADE_HOOKUP_OBJECT (gestion_vol, label52, "label52");
  GLADE_HOOKUP_OBJECT (gestion_vol, label54, "label54");
  GLADE_HOOKUP_OBJECT (gestion_vol, label41, "label41");
  GLADE_HOOKUP_OBJECT (gestion_vol, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (gestion_vol, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (gestion_vol, image13, "image13");
  GLADE_HOOKUP_OBJECT (gestion_vol, label61, "label61");
  GLADE_HOOKUP_OBJECT (gestion_vol, label62, "label62");
  GLADE_HOOKUP_OBJECT (gestion_vol, button9, "button9");
  GLADE_HOOKUP_OBJECT (gestion_vol, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (gestion_vol, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (gestion_vol, image9, "image9");
  GLADE_HOOKUP_OBJECT (gestion_vol, label63, "label63");
  GLADE_HOOKUP_OBJECT (gestion_vol, label59, "label59");
  GLADE_HOOKUP_OBJECT (gestion_vol, label60, "label60");
  GLADE_HOOKUP_OBJECT (gestion_vol, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (gestion_vol, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (gestion_vol, label58, "label58");
  GLADE_HOOKUP_OBJECT (gestion_vol, button2, "button2");
  GLADE_HOOKUP_OBJECT (gestion_vol, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (gestion_vol, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (gestion_vol, image2, "image2");
  GLADE_HOOKUP_OBJECT (gestion_vol, label2, "label2");
  GLADE_HOOKUP_OBJECT (gestion_vol, button3, "button3");
  GLADE_HOOKUP_OBJECT (gestion_vol, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestion_vol, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestion_vol, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestion_vol, label3, "label3");

  return gestion_vol;
}

GtkWidget*
create_window (void)
{
  GtkWidget *window;
  GtkWidget *fixed7;
  GtkWidget *image15;
  GtkWidget *button10;
  GtkWidget *button11;
  GtkWidget *button19;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image27;
  GtkWidget *label113;

  window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window), _("window1"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window), fixed7);

  image15 = create_pixmap (window, "people-inside-commercial-air-plane-1309644 (1).jpg");
  gtk_widget_show (image15);
  gtk_fixed_put (GTK_FIXED (fixed7), image15, 0, 0);
  gtk_widget_set_size_request (image15, 616, 560);

  button10 = gtk_button_new_with_mnemonic (_("Agent"));
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed7), button10, 208, 112);
  gtk_widget_set_size_request (button10, 176, 120);

  button11 = gtk_button_new_with_mnemonic (_("Client"));
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed7), button11, 208, 320);
  gtk_widget_set_size_request (button11, 176, 112);

  button19 = gtk_button_new ();
  gtk_widget_show (button19);
  gtk_fixed_put (GTK_FIXED (fixed7), button19, 24, 504);
  gtk_widget_set_size_request (button19, 88, 37);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button19), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image27 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox17), image27, FALSE, FALSE, 0);

  label113 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label113);
  gtk_box_pack_start (GTK_BOX (hbox17), label113, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);
  g_signal_connect ((gpointer) button19, "clicked",
                    G_CALLBACK (on_button19_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window, window, "window");
  GLADE_HOOKUP_OBJECT (window, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window, image15, "image15");
  GLADE_HOOKUP_OBJECT (window, button10, "button10");
  GLADE_HOOKUP_OBJECT (window, button11, "button11");
  GLADE_HOOKUP_OBJECT (window, button19, "button19");
  GLADE_HOOKUP_OBJECT (window, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window, image27, "image27");
  GLADE_HOOKUP_OBJECT (window, label113, "label113");

  return window;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed10;
  GtkWidget *button15;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image21;
  GtkWidget *label86;
  GtkWidget *notebook2;
  GtkWidget *fixed11;
  GtkWidget *image23;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeview3;
  GtkWidget *label89;
  GtkWidget *button17;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image24;
  GtkWidget *label90;
  GtkWidget *label88;
  GtkWidget *label91;
  GtkWidget *fixed12;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *image25;
  GtkWidget *label92;
  GtkWidget *label93;
  GtkWidget *label94;
  GtkWidget *label95;
  GtkWidget *label96;
  GtkWidget *label97;
  GtkWidget *label98;
  GtkWidget *label99;
  GtkWidget *button18;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image26;
  GtkWidget *label111;
  GtkWidget *label110;
  GtkWidget *label101;
  GtkWidget *label109;
  GtkWidget *label102;
  GtkWidget *label103;
  GtkWidget *label104;
  GtkWidget *label105;
  GtkWidget *label106;
  GtkWidget *label107;
  GtkWidget *label108;
  GtkWidget *label100;
  GtkWidget *label112;
  GtkWidget *button16;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image22;
  GtkWidget *label87;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window1, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (window1), _("Gestion Vols"));
  gtk_window_set_position (GTK_WINDOW (window1), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (window1), FALSE);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (window1), fixed10);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed10), button15, 872, 640);
  gtk_widget_set_size_request (button15, 96, 53);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button15), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image21 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox13), image21, FALSE, FALSE, 0);

  label86 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label86);
  gtk_box_pack_start (GTK_BOX (hbox13), label86, FALSE, FALSE, 0);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_fixed_put (GTK_FIXED (fixed10), notebook2, 0, 0);
  gtk_widget_set_size_request (notebook2, 1600, 640);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed11);

  image23 = create_pixmap (window1, "white-airliner-wing-on-top-of-sea-clouds-2007401 (1).jpg");
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed11), image23, 0, 0);
  gtk_widget_set_size_request (image23, 992, 608);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_fixed_put (GTK_FIXED (fixed11), scrolledwindow3, 0, 72);
  gtk_widget_set_size_request (scrolledwindow3, 584, 384);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeview3);
  gtk_widget_set_size_request (treeview3, 584, 384);

  label89 = gtk_label_new ("");
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed11), label89, 816, 56);
  gtk_widget_set_size_request (label89, 104, 48);

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed11), button17, 384, 504);
  gtk_widget_set_size_request (button17, 96, 53);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button17), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image24 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox15), image24, FALSE, FALSE, 0);

  label90 = gtk_label_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (label90);
  gtk_box_pack_start (GTK_BOX (hbox15), label90, FALSE, FALSE, 0);

  label88 = gtk_label_new (_("<span foreground=\"red\"><b>Selectionner un Vol !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed11), label88, 0, 0);
  gtk_widget_set_size_request (label88, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label88), TRUE);

  label91 = gtk_label_new (_("Afficher"));
  gtk_widget_show (label91);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label91);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed12);

  spinbutton6_adj = gtk_adjustment_new (1, 1, 50, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton6, 744, 264);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  image25 = create_pixmap (window1, "MoDautumn-background-beautiful-bright-627823 (1).jpg");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed12), image25, 0, 0);
  gtk_widget_set_size_request (image25, 1000, 608);

  label92 = gtk_label_new (_("Depart : "));
  gtk_widget_show (label92);
  gtk_fixed_put (GTK_FIXED (fixed12), label92, 208, 128);
  gtk_widget_set_size_request (label92, 128, 48);

  label93 = gtk_label_new (_("Destination : "));
  gtk_widget_show (label93);
  gtk_fixed_put (GTK_FIXED (fixed12), label93, 200, 184);
  gtk_widget_set_size_request (label93, 128, 48);

  label94 = gtk_label_new (_("Companie : "));
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixed12), label94, 192, 248);
  gtk_widget_set_size_request (label94, 128, 48);

  label95 = gtk_label_new (_("Date de depart : "));
  gtk_widget_show (label95);
  gtk_fixed_put (GTK_FIXED (fixed12), label95, 128, 296);
  gtk_widget_set_size_request (label95, 240, 64);

  label96 = gtk_label_new (_("Date de retour : "));
  gtk_widget_show (label96);
  gtk_fixed_put (GTK_FIXED (fixed12), label96, 176, 360);
  gtk_widget_set_size_request (label96, 128, 48);

  label97 = gtk_label_new (_("Vols disponible : "));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed12), label97, 160, 416);
  gtk_widget_set_size_request (label97, 144, 48);

  label98 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed12), label98, 152, 480);
  gtk_widget_set_size_request (label98, 144, 48);

  label99 = gtk_label_new (_("Nombre des vols : "));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed12), label99, 592, 256);
  gtk_widget_set_size_request (label99, 144, 48);

  button18 = gtk_button_new ();
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed12), button18, 704, 352);
  gtk_widget_set_size_request (button18, 96, 53);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button18), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image26 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox16), image26, FALSE, FALSE, 0);

  label111 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label111);
  gtk_box_pack_start (GTK_BOX (hbox16), label111, FALSE, FALSE, 0);

  label110 = gtk_label_new (_("<span foreground=\"blue\"><i>Reservation r\303\251ussite</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed12), label110, 0, 0);
  gtk_widget_set_size_request (label110, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label110), TRUE);

  label101 = gtk_label_new (_("Reserver le Vol : "));
  gtk_widget_show (label101);
  gtk_fixed_put (GTK_FIXED (fixed12), label101, 200, 64);
  gtk_widget_set_size_request (label101, 152, 48);

  label109 = gtk_label_new ("");
  gtk_widget_show (label109);
  gtk_fixed_put (GTK_FIXED (fixed12), label109, 344, 64);
  gtk_widget_set_size_request (label109, 120, 48);

  label102 = gtk_label_new ("");
  gtk_widget_show (label102);
  gtk_fixed_put (GTK_FIXED (fixed12), label102, 360, 128);
  gtk_widget_set_size_request (label102, 128, 48);

  label103 = gtk_label_new ("");
  gtk_widget_show (label103);
  gtk_fixed_put (GTK_FIXED (fixed12), label103, 368, 184);
  gtk_widget_set_size_request (label103, 128, 48);

  label104 = gtk_label_new ("");
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixed12), label104, 368, 248);
  gtk_widget_set_size_request (label104, 128, 48);

  label105 = gtk_label_new ("");
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed12), label105, 312, 296);
  gtk_widget_set_size_request (label105, 240, 64);

  label106 = gtk_label_new ("");
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed12), label106, 360, 360);
  gtk_widget_set_size_request (label106, 128, 48);

  label107 = gtk_label_new ("");
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed12), label107, 352, 416);
  gtk_widget_set_size_request (label107, 144, 48);

  label108 = gtk_label_new ("");
  gtk_widget_show (label108);
  gtk_fixed_put (GTK_FIXED (fixed12), label108, 352, 480);
  gtk_widget_set_size_request (label108, 144, 48);

  label100 = gtk_label_new (_("<span foreground=\"red\"><b> Nombre invalide !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed12), label100, 752, 240);
  gtk_widget_set_size_request (label100, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label100), TRUE);

  label112 = gtk_label_new (_("Reserver"));
  gtk_widget_show (label112);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label112);

  button16 = gtk_button_new ();
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed10), button16, 24, 640);
  gtk_widget_set_size_request (button16, 96, 53);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button16), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image22 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox14), image22, FALSE, FALSE, 0);

  label87 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label87);
  gtk_box_pack_start (GTK_BOX (hbox14), label87, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button17, "clicked",
                    G_CALLBACK (on_button14_clicked),
                    NULL);
  g_signal_connect ((gpointer) button18, "clicked",
                    G_CALLBACK (on_button15_clicked),
                    NULL);
  g_signal_connect ((gpointer) button16, "clicked",
                    G_CALLBACK (on_button16_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window1, button15, "button15");
  GLADE_HOOKUP_OBJECT (window1, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window1, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window1, image21, "image21");
  GLADE_HOOKUP_OBJECT (window1, label86, "label86");
  GLADE_HOOKUP_OBJECT (window1, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (window1, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (window1, image23, "image23");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (window1, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (window1, label89, "label89");
  GLADE_HOOKUP_OBJECT (window1, button17, "button17");
  GLADE_HOOKUP_OBJECT (window1, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window1, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window1, image24, "image24");
  GLADE_HOOKUP_OBJECT (window1, label90, "label90");
  GLADE_HOOKUP_OBJECT (window1, label88, "label88");
  GLADE_HOOKUP_OBJECT (window1, label91, "label91");
  GLADE_HOOKUP_OBJECT (window1, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (window1, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (window1, image25, "image25");
  GLADE_HOOKUP_OBJECT (window1, label92, "label92");
  GLADE_HOOKUP_OBJECT (window1, label93, "label93");
  GLADE_HOOKUP_OBJECT (window1, label94, "label94");
  GLADE_HOOKUP_OBJECT (window1, label95, "label95");
  GLADE_HOOKUP_OBJECT (window1, label96, "label96");
  GLADE_HOOKUP_OBJECT (window1, label97, "label97");
  GLADE_HOOKUP_OBJECT (window1, label98, "label98");
  GLADE_HOOKUP_OBJECT (window1, label99, "label99");
  GLADE_HOOKUP_OBJECT (window1, button18, "button18");
  GLADE_HOOKUP_OBJECT (window1, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window1, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window1, image26, "image26");
  GLADE_HOOKUP_OBJECT (window1, label111, "label111");
  GLADE_HOOKUP_OBJECT (window1, label110, "label110");
  GLADE_HOOKUP_OBJECT (window1, label101, "label101");
  GLADE_HOOKUP_OBJECT (window1, label109, "label109");
  GLADE_HOOKUP_OBJECT (window1, label102, "label102");
  GLADE_HOOKUP_OBJECT (window1, label103, "label103");
  GLADE_HOOKUP_OBJECT (window1, label104, "label104");
  GLADE_HOOKUP_OBJECT (window1, label105, "label105");
  GLADE_HOOKUP_OBJECT (window1, label106, "label106");
  GLADE_HOOKUP_OBJECT (window1, label107, "label107");
  GLADE_HOOKUP_OBJECT (window1, label108, "label108");
  GLADE_HOOKUP_OBJECT (window1, label100, "label100");
  GLADE_HOOKUP_OBJECT (window1, label112, "label112");
  GLADE_HOOKUP_OBJECT (window1, button16, "button16");
  GLADE_HOOKUP_OBJECT (window1, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window1, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window1, image22, "image22");
  GLADE_HOOKUP_OBJECT (window1, label87, "label87");

  return window1;
}

