/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
  GtkWidget *acceuil;
  GtkWidget *gestion_vol;
int
main (int argc, char *argv[])
{


#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("/home/emna/Desktop/gestionVolEMNA/gestionVol/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  acceuil = create_acceuil ();
  gtk_widget_show (acceuil);
/*
  gestion_vol = create_gestion_vol ();
  gtk_widget_show (gestion_vol);*/

  gtk_main ();
  return 0;
}

