/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window3 (void);
GtkWidget* create_window4 (void);
GtkWidget* create_window5 (void);
GtkWidget* create_window6 (void);
GtkWidget* create_window7 (void);
GtkWidget* create_window8 (void);
GtkWidget* create_window9 (void);
GtkWidget* create_window10 (void);
GtkWidget* create_window11 (void);
GtkWidget* create_window12 (void);
GtkWidget* create_window14 (void);
GtkWidget* create_window15 (void);
GtkWidget* create_window16 (void);
GtkWidget* create_window18 (void);
GtkWidget* create_window19 (void);
GtkWidget* create_window20 (void);
GtkWidget* create_window21 (void);
GtkWidget* create_window22 (void);
GtkWidget* create_window23 (void);
GtkWidget* create_window24 (void);
GtkWidget* create_window25 (void);
GtkWidget* create_window26 (void);
